/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_lmp_LmpPlugin_Pair */

#ifndef _Included_jse_lmp_LmpPlugin_Pair
#define _Included_jse_lmp_LmpPlugin_Pair
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    neighborRequestDefault_
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_neighborRequestDefault_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    neighborRequestFull_
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_neighborRequestFull_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    evInit_
 * Signature: (JZZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_evInit_1
  (JNIEnv *, jclass, jlong, jboolean, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomX_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomX_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomF_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomF_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomType_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomType_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomNtypes_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomNtypes_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomNlocal_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomNlocal_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomNghost_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomNghost_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    forceSpecialLj_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_forceSpecialLj_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    forceNewtonPair_
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_forceNewtonPair_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    listInum_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_listInum_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    listIlist_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_listIlist_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    listNumneigh_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_listNumneigh_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    listFirstneigh_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_listFirstneigh_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    evTally_
 * Signature: (JIIIZDDDDDD)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_evTally_1
  (JNIEnv *, jclass, jlong, jint, jint, jint, jboolean, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    evflag_
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_evflag_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    vflagFdotr_
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_vflagFdotr_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    virialFdotrCompute_
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_virialFdotrCompute_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    commMe_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_commMe_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    commNprocs_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_commNprocs_1
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
