/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_lmp_LmpPlugin_Fix */

#ifndef _Included_jse_lmp_LmpPlugin_Fix
#define _Included_jse_lmp_LmpPlugin_Fix
#ifdef __cplusplus
extern "C" {
#endif
#undef jse_lmp_LmpPlugin_Fix_INITIAL_INTEGRATE
#define jse_lmp_LmpPlugin_Fix_INITIAL_INTEGRATE 1L
#undef jse_lmp_LmpPlugin_Fix_POST_INTEGRATE
#define jse_lmp_LmpPlugin_Fix_POST_INTEGRATE 2L
#undef jse_lmp_LmpPlugin_Fix_PRE_EXCHANGE
#define jse_lmp_LmpPlugin_Fix_PRE_EXCHANGE 4L
#undef jse_lmp_LmpPlugin_Fix_PRE_NEIGHBOR
#define jse_lmp_LmpPlugin_Fix_PRE_NEIGHBOR 8L
#undef jse_lmp_LmpPlugin_Fix_POST_NEIGHBOR
#define jse_lmp_LmpPlugin_Fix_POST_NEIGHBOR 16L
#undef jse_lmp_LmpPlugin_Fix_PRE_FORCE
#define jse_lmp_LmpPlugin_Fix_PRE_FORCE 32L
#undef jse_lmp_LmpPlugin_Fix_PRE_REVERSE
#define jse_lmp_LmpPlugin_Fix_PRE_REVERSE 64L
#undef jse_lmp_LmpPlugin_Fix_POST_FORCE
#define jse_lmp_LmpPlugin_Fix_POST_FORCE 128L
#undef jse_lmp_LmpPlugin_Fix_FINAL_INTEGRATE
#define jse_lmp_LmpPlugin_Fix_FINAL_INTEGRATE 256L
#undef jse_lmp_LmpPlugin_Fix_END_OF_STEP
#define jse_lmp_LmpPlugin_Fix_END_OF_STEP 512L
#undef jse_lmp_LmpPlugin_Fix_POST_RUN
#define jse_lmp_LmpPlugin_Fix_POST_RUN 1024L
#undef jse_lmp_LmpPlugin_Fix_MIN_PRE_EXCHANGE
#define jse_lmp_LmpPlugin_Fix_MIN_PRE_EXCHANGE 65536L
#undef jse_lmp_LmpPlugin_Fix_MIN_PRE_NEIGHBOR
#define jse_lmp_LmpPlugin_Fix_MIN_PRE_NEIGHBOR 131072L
#undef jse_lmp_LmpPlugin_Fix_MIN_POST_NEIGHBOR
#define jse_lmp_LmpPlugin_Fix_MIN_POST_NEIGHBOR 262144L
#undef jse_lmp_LmpPlugin_Fix_MIN_PRE_FORCE
#define jse_lmp_LmpPlugin_Fix_MIN_PRE_FORCE 524288L
#undef jse_lmp_LmpPlugin_Fix_MIN_PRE_REVERSE
#define jse_lmp_LmpPlugin_Fix_MIN_PRE_REVERSE 1048576L
#undef jse_lmp_LmpPlugin_Fix_MIN_POST_FORCE
#define jse_lmp_LmpPlugin_Fix_MIN_POST_FORCE 2097152L
#undef jse_lmp_LmpPlugin_Fix_NO_BOX_CHANGE
#define jse_lmp_LmpPlugin_Fix_NO_BOX_CHANGE 0L
#undef jse_lmp_LmpPlugin_Fix_BOX_CHANGE_ANY
#define jse_lmp_LmpPlugin_Fix_BOX_CHANGE_ANY 1L
#undef jse_lmp_LmpPlugin_Fix_BOX_CHANGE_DOMAIN
#define jse_lmp_LmpPlugin_Fix_BOX_CHANGE_DOMAIN 2L
#undef jse_lmp_LmpPlugin_Fix_BOX_CHANGE_X
#define jse_lmp_LmpPlugin_Fix_BOX_CHANGE_X 4L
#undef jse_lmp_LmpPlugin_Fix_BOX_CHANGE_Y
#define jse_lmp_LmpPlugin_Fix_BOX_CHANGE_Y 8L
#undef jse_lmp_LmpPlugin_Fix_BOX_CHANGE_Z
#define jse_lmp_LmpPlugin_Fix_BOX_CHANGE_Z 16L
#undef jse_lmp_LmpPlugin_Fix_BOX_CHANGE_YZ
#define jse_lmp_LmpPlugin_Fix_BOX_CHANGE_YZ 32L
#undef jse_lmp_LmpPlugin_Fix_BOX_CHANGE_XZ
#define jse_lmp_LmpPlugin_Fix_BOX_CHANGE_XZ 64L
#undef jse_lmp_LmpPlugin_Fix_BOX_CHANGE_XY
#define jse_lmp_LmpPlugin_Fix_BOX_CHANGE_XY 128L
#undef jse_lmp_LmpPlugin_Fix_BOX_CHANGE_SIZE
#define jse_lmp_LmpPlugin_Fix_BOX_CHANGE_SIZE 28L
#undef jse_lmp_LmpPlugin_Fix_BOX_CHANGE_SHAPE
#define jse_lmp_LmpPlugin_Fix_BOX_CHANGE_SHAPE 224L
/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setBoxChange0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setBoxChange0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setNoChangeBox0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setNoChangeBox0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setForceReneighbor0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setForceReneighbor0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setNextReneighbor0
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setNextReneighbor0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    nextReneighbor0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_nextReneighbor0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setNevery0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setNevery0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setEnergyGlobalFlag0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setEnergyGlobalFlag0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setEnergyPeratomFlag0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setEnergyPeratomFlag0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setVirialGlobalFlag0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setVirialGlobalFlag0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setVirialPeratomFlag0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setVirialPeratomFlag0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setTimeDepend0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setTimeDepend0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setDynamicGroupAllow0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setDynamicGroupAllow0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setScalarFlag0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setScalarFlag0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setVectorFlag0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setVectorFlag0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setArrayFlag0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setArrayFlag0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setSizeVector0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setSizeVector0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setSizeArrayRows0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setSizeArrayRows0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setSizeArrayCols0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setSizeArrayCols0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setGlobalFreq0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setGlobalFreq0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setExtscalar0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setExtscalar0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setExtvector0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setExtvector0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setExtarray0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setExtarray0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setPeratomFlag0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setPeratomFlag0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setSizePeratomCols0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setSizePeratomCols0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setPeratomFreq0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setPeratomFreq0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setVectorAtom0
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setVectorAtom0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setArrayAtom0
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setArrayAtom0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setCommForward0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setCommForward0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setCommReverse0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setCommReverse0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    findVariable0
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_findVariable0
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    computeVariable0
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_computeVariable0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    citemeAdd0
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_citemeAdd0
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    neighborRequestDefault0
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_neighborRequestDefault0
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    neighborRequestFull0
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_neighborRequestFull0
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    neighborRequestOccasional0
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_neighborRequestOccasional0
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    neighborRequestOccasionalFull0
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_neighborRequestOccasionalFull0
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    neighborBuildOne0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_neighborBuildOne0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    neighborAgo0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_neighborAgo0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    neighborCutneighmin0
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_neighborCutneighmin0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    neighborCutneighmax0
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_neighborCutneighmax0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    neighborCuttype0
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_neighborCuttype0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    neighborSkin0
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_neighborSkin0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    igroup0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_igroup0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    groupbit0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_groupbit0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    atomX0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_atomX0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    atomV0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_atomV0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    atomF0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_atomF0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    atomMask0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_atomMask0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    atomTag0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_atomTag0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    atomType0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_atomType0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    atomMass0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_atomMass0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    atomExtract0
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_atomExtract0
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    atomNatoms0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_atomNatoms0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    atomNtypes0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_atomNtypes0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    atomNlocal0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_atomNlocal0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    atomNmax0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_atomNmax0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    atomNghost0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_atomNghost0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainTriclinic0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainTriclinic0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainXy0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainXy0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainXz0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainXz0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainYz0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainYz0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainXprd0
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainXprd0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainYprd0
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainYprd0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainZprd0
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainZprd0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainH0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainH0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainHInv0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainHInv0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainBoxlo0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainBoxlo0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainBoxhi0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainBoxhi0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainBoxloLamda0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainBoxloLamda0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainBoxhiLamda0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainBoxhiLamda0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainSublo0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainSublo0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainSubhi0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainSubhi0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainSubloLamda0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainSubloLamda0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainSubhiLamda0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainSubhiLamda0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainX2lamda0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainX2lamda0__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainX2lamda0
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainX2lamda0__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainLamda2x0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainLamda2x0__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainLamda2x0
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainLamda2x0__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainSetGlobalBox0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainSetGlobalBox0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainSetLocalBox0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainSetLocalBox0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    listGnum0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_listGnum0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    listInum0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_listInum0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    listIlist0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_listIlist0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    listNumneigh0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_listNumneigh0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    listFirstneigh0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_listFirstneigh0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    forceBoltz0
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_forceBoltz0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    forcePairCutforce0
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_forcePairCutforce0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    dt0
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_dt0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    ntimestep0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_ntimestep0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    firststep0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_firststep0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    laststep0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_laststep0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    beginstep0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_beginstep0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    endstep0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_endstep0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    commMe0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_commMe0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    commNprocs0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_commNprocs0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    commBarrier0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_commBarrier0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    commWorld0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_commWorld0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    commCutghostuser0
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_commCutghostuser0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    commForwardComm0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_commForwardComm0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    commForwardCommThis0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_commForwardCommThis0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    commReverseComm0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_commReverseComm0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    commReverseCommThis0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_commReverseCommThis0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    unitStyle0
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jse_lmp_LmpPlugin_00024Fix_unitStyle0
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
