/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_lmp_LmpPlugin_Fix */

#ifndef _Included_jse_lmp_LmpPlugin_Fix
#define _Included_jse_lmp_LmpPlugin_Fix
#ifdef __cplusplus
extern "C" {
#endif
#undef jse_lmp_LmpPlugin_Fix_INITIAL_INTEGRATE
#define jse_lmp_LmpPlugin_Fix_INITIAL_INTEGRATE 1L
#undef jse_lmp_LmpPlugin_Fix_POST_INTEGRATE
#define jse_lmp_LmpPlugin_Fix_POST_INTEGRATE 2L
#undef jse_lmp_LmpPlugin_Fix_PRE_EXCHANGE
#define jse_lmp_LmpPlugin_Fix_PRE_EXCHANGE 4L
#undef jse_lmp_LmpPlugin_Fix_PRE_NEIGHBOR
#define jse_lmp_LmpPlugin_Fix_PRE_NEIGHBOR 8L
#undef jse_lmp_LmpPlugin_Fix_POST_NEIGHBOR
#define jse_lmp_LmpPlugin_Fix_POST_NEIGHBOR 16L
#undef jse_lmp_LmpPlugin_Fix_PRE_FORCE
#define jse_lmp_LmpPlugin_Fix_PRE_FORCE 32L
#undef jse_lmp_LmpPlugin_Fix_PRE_REVERSE
#define jse_lmp_LmpPlugin_Fix_PRE_REVERSE 64L
#undef jse_lmp_LmpPlugin_Fix_POST_FORCE
#define jse_lmp_LmpPlugin_Fix_POST_FORCE 128L
#undef jse_lmp_LmpPlugin_Fix_FINAL_INTEGRATE
#define jse_lmp_LmpPlugin_Fix_FINAL_INTEGRATE 256L
#undef jse_lmp_LmpPlugin_Fix_END_OF_STEP
#define jse_lmp_LmpPlugin_Fix_END_OF_STEP 512L
#undef jse_lmp_LmpPlugin_Fix_POST_RUN
#define jse_lmp_LmpPlugin_Fix_POST_RUN 1024L
#undef jse_lmp_LmpPlugin_Fix_MIN_PRE_EXCHANGE
#define jse_lmp_LmpPlugin_Fix_MIN_PRE_EXCHANGE 65536L
#undef jse_lmp_LmpPlugin_Fix_MIN_PRE_NEIGHBOR
#define jse_lmp_LmpPlugin_Fix_MIN_PRE_NEIGHBOR 131072L
#undef jse_lmp_LmpPlugin_Fix_MIN_POST_NEIGHBOR
#define jse_lmp_LmpPlugin_Fix_MIN_POST_NEIGHBOR 262144L
#undef jse_lmp_LmpPlugin_Fix_MIN_PRE_FORCE
#define jse_lmp_LmpPlugin_Fix_MIN_PRE_FORCE 524288L
#undef jse_lmp_LmpPlugin_Fix_MIN_PRE_REVERSE
#define jse_lmp_LmpPlugin_Fix_MIN_PRE_REVERSE 1048576L
#undef jse_lmp_LmpPlugin_Fix_MIN_POST_FORCE
#define jse_lmp_LmpPlugin_Fix_MIN_POST_FORCE 2097152L
#undef jse_lmp_LmpPlugin_Fix_NO_BOX_CHANGE
#define jse_lmp_LmpPlugin_Fix_NO_BOX_CHANGE 0L
#undef jse_lmp_LmpPlugin_Fix_BOX_CHANGE_ANY
#define jse_lmp_LmpPlugin_Fix_BOX_CHANGE_ANY 1L
#undef jse_lmp_LmpPlugin_Fix_BOX_CHANGE_DOMAIN
#define jse_lmp_LmpPlugin_Fix_BOX_CHANGE_DOMAIN 2L
#undef jse_lmp_LmpPlugin_Fix_BOX_CHANGE_X
#define jse_lmp_LmpPlugin_Fix_BOX_CHANGE_X 4L
#undef jse_lmp_LmpPlugin_Fix_BOX_CHANGE_Y
#define jse_lmp_LmpPlugin_Fix_BOX_CHANGE_Y 8L
#undef jse_lmp_LmpPlugin_Fix_BOX_CHANGE_Z
#define jse_lmp_LmpPlugin_Fix_BOX_CHANGE_Z 16L
#undef jse_lmp_LmpPlugin_Fix_BOX_CHANGE_YZ
#define jse_lmp_LmpPlugin_Fix_BOX_CHANGE_YZ 32L
#undef jse_lmp_LmpPlugin_Fix_BOX_CHANGE_XZ
#define jse_lmp_LmpPlugin_Fix_BOX_CHANGE_XZ 64L
#undef jse_lmp_LmpPlugin_Fix_BOX_CHANGE_XY
#define jse_lmp_LmpPlugin_Fix_BOX_CHANGE_XY 128L
#undef jse_lmp_LmpPlugin_Fix_BOX_CHANGE_SIZE
#define jse_lmp_LmpPlugin_Fix_BOX_CHANGE_SIZE 28L
#undef jse_lmp_LmpPlugin_Fix_BOX_CHANGE_SHAPE
#define jse_lmp_LmpPlugin_Fix_BOX_CHANGE_SHAPE 224L
/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setBoxChange_
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setBoxChange_1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setNoChangeBox_
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setNoChangeBox_1
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setForceReneighbor_
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setForceReneighbor_1
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setNextReneighbor_
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setNextReneighbor_1
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    nextReneighbor_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_nextReneighbor_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setNevery_
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setNevery_1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setEnergyGlobalFlag_
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setEnergyGlobalFlag_1
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setEnergyPeratomFlag_
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setEnergyPeratomFlag_1
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setVirialGlobalFlag_
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setVirialGlobalFlag_1
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setVirialPeratomFlag_
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setVirialPeratomFlag_1
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setTimeDepend_
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setTimeDepend_1
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setDynamicGroupAllow_
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setDynamicGroupAllow_1
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setScalarFlag_
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setScalarFlag_1
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setVectorFlag_
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setVectorFlag_1
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setArrayFlag_
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setArrayFlag_1
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setSizeVector_
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setSizeVector_1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setSizeArrayRows_
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setSizeArrayRows_1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setSizeArrayCols_
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setSizeArrayCols_1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setGlobalFreq_
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setGlobalFreq_1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setExtscalar_
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setExtscalar_1
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setExtvector_
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setExtvector_1
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    setExtarray_
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_setExtarray_1
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    findVariable_
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_findVariable_1
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    computeVariable_
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_computeVariable_1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    neighborRequestDefault_
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_neighborRequestDefault_1
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    neighborRequestFull_
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_neighborRequestFull_1
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    neighborRequestOccasional_
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_neighborRequestOccasional_1
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    neighborRequestOccasionalFull_
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_neighborRequestOccasionalFull_1
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    neighborBuildOne_
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_neighborBuildOne_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    neighborCutneighmin_
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_neighborCutneighmin_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    neighborCutneighmax_
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_neighborCutneighmax_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    neighborCuttype_
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_neighborCuttype_1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    neighborSkin_
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_neighborSkin_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    igroup_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_igroup_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    groupbit_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_groupbit_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    atomX_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_atomX_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    atomF_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_atomF_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    atomMask_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_atomMask_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    atomType_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_atomType_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    atomNatoms_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_atomNatoms_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    atomNtypes_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_atomNtypes_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    atomNlocal_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_atomNlocal_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    atomNmax_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_atomNmax_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    atomNghost_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_atomNghost_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainXy_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainXy_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainXz_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainXz_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainYz_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainYz_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainXprd_
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainXprd_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainYprd_
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainYprd_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainZprd_
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainZprd_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainH_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainH_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainHInv_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainHInv_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainBoxlo_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainBoxlo_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainBoxhi_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainBoxhi_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainX2lamda_
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainX2lamda_1__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainX2lamda_
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainX2lamda_1__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainLamda2x_
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainLamda2x_1__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainLamda2x_
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainLamda2x_1__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainSetGlobalBox_
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainSetGlobalBox_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    domainSetLocalBox_
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Fix_domainSetLocalBox_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    listGnum_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_listGnum_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    listInum_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_listInum_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    listIlist_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_listIlist_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    listNumneigh_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_listNumneigh_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    listFirstneigh_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_listFirstneigh_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    forceBoltz_
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_forceBoltz_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    forcePairCutforce_
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_forcePairCutforce_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    dt_
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_dt_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    ntimestep_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_ntimestep_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    firststep_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_firststep_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    laststep_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_laststep_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    beginstep_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_beginstep_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    endstep_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_endstep_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    commMe_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_commMe_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    commNprocs_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Fix_commNprocs_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    commWorld_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Fix_commWorld_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    commCutghostuser_
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Fix_commCutghostuser_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Fix
 * Method:    unitStyle_
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jse_lmp_LmpPlugin_00024Fix_unitStyle_1
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
