/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_lmp_LmpPlugin_Pair */

#ifndef _Included_jse_lmp_LmpPlugin_Pair
#define _Included_jse_lmp_LmpPlugin_Pair
#ifdef __cplusplus
extern "C" {
#endif
#undef jse_lmp_LmpPlugin_Pair_CENTROID_SAME
#define jse_lmp_LmpPlugin_Pair_CENTROID_SAME 0L
#undef jse_lmp_LmpPlugin_Pair_CENTROID_AVAIL
#define jse_lmp_LmpPlugin_Pair_CENTROID_AVAIL 1L
#undef jse_lmp_LmpPlugin_Pair_CENTROID_NOTAVAIL
#define jse_lmp_LmpPlugin_Pair_CENTROID_NOTAVAIL 2L
/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    findVariable0
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_findVariable0
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    computeVariable0
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Pair_computeVariable0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    citemeAdd0
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_citemeAdd0
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    setSingleEnable0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_setSingleEnable0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    setOneCoeff0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_setOneCoeff0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    setManybodyFlag0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_setManybodyFlag0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    setUnitConvertFlag0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_setUnitConvertFlag0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    setNoVirialFdotrCompute0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_setNoVirialFdotrCompute0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    setFinitecutflag0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_setFinitecutflag0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    setGhostneigh0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_setGhostneigh0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    setCentroidstressflag0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_setCentroidstressflag0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    setCommForward0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_setCommForward0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    setCommReverse0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_setCommReverse0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    setCommReverseOff0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_setCommReverseOff0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    neighborRequestDefault0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_neighborRequestDefault0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    neighborRequestFull0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_neighborRequestFull0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    neighborAgo0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_neighborAgo0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomX0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomX0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomV0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomV0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomF0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomF0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomTag0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomTag0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomType0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomType0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomMass0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomMass0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomExtract0
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomExtract0
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomNatoms0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomNatoms0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomNtypes0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomNtypes0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomNlocal0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomNlocal0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomNghost0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomNghost0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomNmax0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomNmax0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    forceSpecialLj0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_forceSpecialLj0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    forceNewtonPair0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_forceNewtonPair0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    listGnum0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_listGnum0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    listInum0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_listInum0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    listIlist0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_listIlist0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    listNumneigh0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_listNumneigh0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    listFirstneigh0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_listFirstneigh0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    cutsq0
 * Signature: (JII)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Pair_cutsq0
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    engVdwl0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_engVdwl0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    engCoul0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_engCoul0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    eatom0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_eatom0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    virial0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_virial0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    vatom0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_vatom0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    cvatom0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_cvatom0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    evTally0
 * Signature: (JIIIZDDDDDD)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_evTally0
  (JNIEnv *, jclass, jlong, jint, jint, jint, jboolean, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    evTallyFull0
 * Signature: (JIDDDDDD)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_evTallyFull0
  (JNIEnv *, jclass, jlong, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    evTallyXYZ0
 * Signature: (JIIIZDDDDDDDD)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_evTallyXYZ0
  (JNIEnv *, jclass, jlong, jint, jint, jint, jboolean, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    evTallyXYZFull0
 * Signature: (JIDDDDDDDD)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_evTallyXYZFull0
  (JNIEnv *, jclass, jlong, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    evflag0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_evflag0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    vflagEither0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_vflagEither0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    vflagGlobal0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_vflagGlobal0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    vflagAtom0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_vflagAtom0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    cvflagAtom0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_cvflagAtom0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    eflagEither0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_eflagEither0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    eflagGlobal0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_eflagGlobal0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    eflagAtom0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_eflagAtom0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    vflagFdotr0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_vflagFdotr0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    virialFdotrCompute0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_virialFdotrCompute0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    commMe0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_commMe0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    commNprocs0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_commNprocs0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    commBarrier0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_commBarrier0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    commWorld0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_commWorld0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    commForwardComm0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_commForwardComm0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    commForwardCommThis0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_commForwardCommThis0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    commReverseComm0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_commReverseComm0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    commReverseCommThis0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_commReverseCommThis0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    unitStyle0
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jse_lmp_LmpPlugin_00024Pair_unitStyle0
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
