/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_lmp_LmpPlugin_Pair */

#ifndef _Included_jse_lmp_LmpPlugin_Pair
#define _Included_jse_lmp_LmpPlugin_Pair
#ifdef __cplusplus
extern "C" {
#endif
#undef jse_lmp_LmpPlugin_Pair_CENTROID_SAME
#define jse_lmp_LmpPlugin_Pair_CENTROID_SAME 0L
#undef jse_lmp_LmpPlugin_Pair_CENTROID_AVAIL
#define jse_lmp_LmpPlugin_Pair_CENTROID_AVAIL 1L
#undef jse_lmp_LmpPlugin_Pair_CENTROID_NOTAVAIL
#define jse_lmp_LmpPlugin_Pair_CENTROID_NOTAVAIL 2L
/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    findVariable_
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_findVariable_1
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    computeVariable_
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Pair_computeVariable_1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    setSingleEnable_
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_setSingleEnable_1
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    setOneCoeff_
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_setOneCoeff_1
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    setManybodyFlag_
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_setManybodyFlag_1
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    setUnitConvertFlag_
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_setUnitConvertFlag_1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    setNoVirialFdotrCompute_
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_setNoVirialFdotrCompute_1
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    setFinitecutflag_
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_setFinitecutflag_1
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    setGhostneigh_
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_setGhostneigh_1
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    setCentroidstressflag_
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_setCentroidstressflag_1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    neighborRequestDefault_
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_neighborRequestDefault_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    neighborRequestFull_
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_neighborRequestFull_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomX_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomX_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomF_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomF_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomType_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomType_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomNatoms_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomNatoms_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomNtypes_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomNtypes_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomNlocal_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomNlocal_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomNghost_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomNghost_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    atomNmax_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_atomNmax_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    forceSpecialLj_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_forceSpecialLj_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    forceNewtonPair_
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_forceNewtonPair_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    listGnum_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_listGnum_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    listInum_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_listInum_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    listIlist_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_listIlist_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    listNumneigh_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_listNumneigh_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    listFirstneigh_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_listFirstneigh_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    cutsq_
 * Signature: (JII)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_LmpPlugin_00024Pair_cutsq_1
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    engVdwl_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_engVdwl_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    engCoul_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_engCoul_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    eatom_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_eatom_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    virial_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_virial_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    vatom_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_vatom_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    cvatom_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_cvatom_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    evTally_
 * Signature: (JIIIZDDDDDD)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_evTally_1
  (JNIEnv *, jclass, jlong, jint, jint, jint, jboolean, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    evTallyFull_
 * Signature: (JIDDDDDD)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_evTallyFull_1
  (JNIEnv *, jclass, jlong, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    evTallyXYZ_
 * Signature: (JIIIZDDDDDDDD)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_evTallyXYZ_1
  (JNIEnv *, jclass, jlong, jint, jint, jint, jboolean, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    evTallyXYZFull_
 * Signature: (JIDDDDDDDD)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_evTallyXYZFull_1
  (JNIEnv *, jclass, jlong, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    evflag_
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_evflag_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    vflagEither_
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_vflagEither_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    vflagGlobal_
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_vflagGlobal_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    vflagAtom_
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_vflagAtom_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    cvflagAtom_
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_cvflagAtom_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    eflagEither_
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_eflagEither_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    eflagGlobal_
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_eflagGlobal_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    eflagAtom_
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_eflagAtom_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    vflagFdotr_
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_LmpPlugin_00024Pair_vflagFdotr_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    virialFdotrCompute_
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_LmpPlugin_00024Pair_virialFdotrCompute_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    commMe_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_commMe_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    commNprocs_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_LmpPlugin_00024Pair_commNprocs_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    commWorld_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_LmpPlugin_00024Pair_commWorld_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_LmpPlugin_Pair
 * Method:    unitStyle_
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jse_lmp_LmpPlugin_00024Pair_unitStyle_1
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
