/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_gpu_DoubleCudaPointer */

#ifndef _Included_jse_gpu_DoubleCudaPointer
#define _Included_jse_gpu_DoubleCudaPointer
#ifdef __cplusplus
extern "C" {
#endif
#undef jse_gpu_DoubleCudaPointer_TYPE_SIZE
#define jse_gpu_DoubleCudaPointer_TYPE_SIZE 1i64
/*
 * Class:     jse_gpu_DoubleCudaPointer
 * Method:    fill0
 * Signature: (J[DII)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_DoubleCudaPointer_fill0
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jint);

/*
 * Class:     jse_gpu_DoubleCudaPointer
 * Method:    fillF0
 * Signature: (J[FII)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_DoubleCudaPointer_fillF0
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jint);

/*
 * Class:     jse_gpu_DoubleCudaPointer
 * Method:    fillF1
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_DoubleCudaPointer_fillF1
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jse_gpu_DoubleCudaPointer
 * Method:    parse2dest0
 * Signature: (J[DII)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_DoubleCudaPointer_parse2dest0
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jint);

/*
 * Class:     jse_gpu_DoubleCudaPointer
 * Method:    parse2destF0
 * Signature: (J[FII)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_DoubleCudaPointer_parse2destF0
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jint);

/*
 * Class:     jse_gpu_DoubleCudaPointer
 * Method:    parse2destF1
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_DoubleCudaPointer_parse2destF1
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
