/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_gpu_Int64CudaPointer */

#ifndef _Included_jse_gpu_Int64CudaPointer
#define _Included_jse_gpu_Int64CudaPointer
#ifdef __cplusplus
extern "C" {
#endif
#undef jse_gpu_Int64CudaPointer_TYPE_SIZE
#define jse_gpu_Int64CudaPointer_TYPE_SIZE 1i64
/*
 * Class:     jse_gpu_Int64CudaPointer
 * Method:    fill0
 * Signature: (J[JII)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_Int64CudaPointer_fill0
  (JNIEnv *, jclass, jlong, jlongArray, jint, jint);

/*
 * Class:     jse_gpu_Int64CudaPointer
 * Method:    parse2dest0
 * Signature: (J[JII)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_Int64CudaPointer_parse2dest0
  (JNIEnv *, jclass, jlong, jlongArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
