/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_gpu_IntCudaPointer */

#ifndef _Included_jse_gpu_IntCudaPointer
#define _Included_jse_gpu_IntCudaPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_gpu_IntCudaPointer
 * Method:    fill_
 * Signature: (J[III)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_IntCudaPointer_fill_1
  (JNIEnv *, jclass, jlong, jintArray, jint, jint);

/*
 * Class:     jse_gpu_IntCudaPointer
 * Method:    parse2dest_
 * Signature: (J[III)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_IntCudaPointer_parse2dest_1
  (JNIEnv *, jclass, jlong, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
