/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_gpu_Int64CudaPointer */

#ifndef _Included_jse_gpu_Int64CudaPointer
#define _Included_jse_gpu_Int64CudaPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_gpu_Int64CudaPointer
 * Method:    fill_
 * Signature: (J[JII)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_Int64CudaPointer_fill_1
  (JNIEnv *, jclass, jlong, jlongArray, jint, jint);

/*
 * Class:     jse_gpu_Int64CudaPointer
 * Method:    parse2dest_
 * Signature: (J[JII)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_Int64CudaPointer_parse2dest_1
  (JNIEnv *, jclass, jlong, jlongArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
