/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_gpu_CudaCore */

#ifndef _Included_jse_gpu_CudaCore
#define _Included_jse_gpu_CudaCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_gpu_CudaCore
 * Method:    cudaDeviceSynchronize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jse_gpu_CudaCore_cudaDeviceSynchronize
  (JNIEnv *, jclass);

/*
 * Class:     jse_gpu_CudaCore
 * Method:    cudaMalloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_jse_gpu_CudaCore_cudaMalloc
  (JNIEnv *, jclass, jint);

/*
 * Class:     jse_gpu_CudaCore
 * Method:    cudaFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_CudaCore_cudaFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_gpu_CudaCore
 * Method:    cudaMemcpyH2D
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_CudaCore_cudaMemcpyH2D
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     jse_gpu_CudaCore
 * Method:    cudaMemcpyD2H
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_CudaCore_cudaMemcpyD2H
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     jse_gpu_CudaCore
 * Method:    cudaMemcpyD2D
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_CudaCore_cudaMemcpyD2D
  (JNIEnv *, jclass, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
