/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_gpu_NestedCudaPointer */

#ifndef _Included_jse_gpu_NestedCudaPointer
#define _Included_jse_gpu_NestedCudaPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_gpu_NestedCudaPointer
 * Method:    typeSize_
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_gpu_NestedCudaPointer_typeSize_1
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
