/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_gpu_IntCudaPointer */

#ifndef _Included_jse_gpu_IntCudaPointer
#define _Included_jse_gpu_IntCudaPointer
#ifdef __cplusplus
extern "C" {
#endif
#undef jse_gpu_IntCudaPointer_TYPE_SIZE
#define jse_gpu_IntCudaPointer_TYPE_SIZE 1i64
/*
 * Class:     jse_gpu_IntCudaPointer
 * Method:    fill0
 * Signature: (J[III)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_IntCudaPointer_fill0
  (JNIEnv *, jclass, jlong, jintArray, jint, jint);

/*
 * Class:     jse_gpu_IntCudaPointer
 * Method:    parse2dest0
 * Signature: (J[III)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_IntCudaPointer_parse2dest0
  (JNIEnv *, jclass, jlong, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
