/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_gpu_CudaCore */

#ifndef _Included_jse_gpu_CudaCore
#define _Included_jse_gpu_CudaCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_gpu_CudaCore
 * Method:    cudaDeviceSynchronize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jse_gpu_CudaCore_cudaDeviceSynchronize
  (JNIEnv *, jclass);

/*
 * Class:     jse_gpu_CudaCore
 * Method:    cudaExceptionCheck
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_CudaCore_cudaExceptionCheck
  (JNIEnv *, jclass, jint);

/*
 * Class:     jse_gpu_CudaCore
 * Method:    cudaGetDeviceCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_gpu_CudaCore_cudaGetDeviceCount
  (JNIEnv *, jclass);

/*
 * Class:     jse_gpu_CudaCore
 * Method:    cudaSetDevice
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_CudaCore_cudaSetDevice
  (JNIEnv *, jclass, jint);

/*
 * Class:     jse_gpu_CudaCore
 * Method:    cudaGetDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_gpu_CudaCore_cudaGetDevice
  (JNIEnv *, jclass);

/*
 * Class:     jse_gpu_CudaCore
 * Method:    cudaMalloc0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_gpu_CudaCore_cudaMalloc0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_gpu_CudaCore
 * Method:    cudaFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_CudaCore_cudaFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_gpu_CudaCore
 * Method:    cudaMemcpyH2D
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_CudaCore_cudaMemcpyH2D
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jse_gpu_CudaCore
 * Method:    cudaMemcpyD2H
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_CudaCore_cudaMemcpyD2H
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jse_gpu_CudaCore
 * Method:    cudaMemcpyD2D
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_CudaCore_cudaMemcpyD2D
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jse_gpu_CudaCore
 * Method:    cudaMemset
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_CudaCore_cudaMemset
  (JNIEnv *, jclass, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
