/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_gpu_FloatCudaPointer */

#ifndef _Included_jse_gpu_FloatCudaPointer
#define _Included_jse_gpu_FloatCudaPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_gpu_FloatCudaPointer
 * Method:    fill_
 * Signature: (J[FII)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_FloatCudaPointer_fill_1
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jint);

/*
 * Class:     jse_gpu_FloatCudaPointer
 * Method:    fillD_
 * Signature: (J[DII)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_FloatCudaPointer_fillD_1
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jint);

/*
 * Class:     jse_gpu_FloatCudaPointer
 * Method:    parse2dest_
 * Signature: (J[FII)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_FloatCudaPointer_parse2dest_1
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jint);

/*
 * Class:     jse_gpu_FloatCudaPointer
 * Method:    parse2destD_
 * Signature: (J[DII)V
 */
JNIEXPORT void JNICALL Java_jse_gpu_FloatCudaPointer_parse2destD_1
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
