/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jep_python_PyCallable */

#ifndef _Included_jep_python_PyCallable
#define _Included_jep_python_PyCallable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jep_python_PyCallable
 * Method:    call
 * Signature: (JJ[Ljava/lang/Object;Ljava/util/Map;Ljava/lang/Class;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_jep_python_PyCallable_call
  (JNIEnv *, jobject, jlong, jlong, jobjectArray, jobject, jclass);

#ifdef __cplusplus
}
#endif
#endif
