/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jep_python_PyPointer */

#ifndef _Included_jep_python_PyPointer
#define _Included_jep_python_PyPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jep_python_PyPointer
 * Method:    decref
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_jep_python_PyPointer_decref
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
