/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jep_python_PyObject */

#ifndef _Included_jep_python_PyObject
#define _Included_jep_python_PyObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jep_python_PyObject
 * Method:    getAttr
 * Signature: (JJLjava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_jep_python_PyObject_getAttr
  (JNIEnv *, jobject, jlong, jlong, jstring, jclass);

/*
 * Class:     jep_python_PyObject
 * Method:    setAttr
 * Signature: (JJLjava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_jep_python_PyObject_setAttr
  (JNIEnv *, jobject, jlong, jlong, jstring, jobject);

/*
 * Class:     jep_python_PyObject
 * Method:    delAttr
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jep_python_PyObject_delAttr
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     jep_python_PyObject
 * Method:    equals
 * Signature: (JJLjava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_jep_python_PyObject_equals
  (JNIEnv *, jobject, jlong, jlong, jobject);

/*
 * Class:     jep_python_PyObject
 * Method:    toString
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jep_python_PyObject_toString
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     jep_python_PyObject
 * Method:    hashCode
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jep_python_PyObject_hashCode
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     jep_python_PyObject
 * Method:    as
 * Signature: (JJLjava/lang/Class;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_jep_python_PyObject_as
  (JNIEnv *, jobject, jlong, jlong, jclass);

#ifdef __cplusplus
}
#endif
#endif
