/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jep_python_InvocationHandler */

#ifndef _Included_jep_python_InvocationHandler
#define _Included_jep_python_InvocationHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jep_python_InvocationHandler
 * Method:    invoke
 * Signature: (Ljava/lang/Object;JJLjava/lang/reflect/Method;[Ljava/lang/Object;Z)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_jep_python_InvocationHandler_invoke
  (JNIEnv *, jclass, jobject, jlong, jlong, jobject, jobjectArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
