/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jep_Jep */

#ifndef _Included_jep_Jep
#define _Included_jep_Jep
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jep_Jep
 * Method:    init
 * Signature: (Ljava/lang/ClassLoader;ZZZIIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_jep_Jep_init
  (JNIEnv *, jobject, jobject, jboolean, jboolean, jboolean, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     jep_Jep
 * Method:    run
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jep_Jep_run
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     jep_Jep
 * Method:    invoke
 * Signature: (JLjava/lang/String;[Ljava/lang/Object;Ljava/util/Map;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_jep_Jep_invoke
  (JNIEnv *, jobject, jlong, jstring, jobjectArray, jobject);

/*
 * Class:     jep_Jep
 * Method:    compileString
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jep_Jep_compileString
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     jep_Jep
 * Method:    eval
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jep_Jep_eval
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     jep_Jep
 * Method:    exec
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jep_Jep_exec
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     jep_Jep
 * Method:    getValue
 * Signature: (JLjava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_jep_Jep_getValue
  (JNIEnv *, jobject, jlong, jstring, jclass);

/*
 * Class:     jep_Jep
 * Method:    set
 * Signature: (JLjava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_jep_Jep_set
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     jep_Jep
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jep_Jep_close
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
