/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_parallel_MPI_Native */

#ifndef _Included_jse_parallel_MPI_Native
#define _Included_jse_parallel_MPI_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiGroupNull0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiGroupNull0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiGroupEmpty0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiGroupEmpty0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiCommNull0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiCommNull0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiCommWorld0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiCommWorld0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiCommSelf0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiCommSelf0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiOpNull0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiOpNull0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiMax0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiMax0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiMin0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiMin0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiSum0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiSum0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiProd0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiProd0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiLand0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiLand0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiBand0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiBand0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiLor0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiLor0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiBor0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiBor0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiLxor0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiLxor0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiBxor0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiBxor0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiMinloc0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiMinloc0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiMaxloc0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiMaxloc0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiReplace0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiReplace0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiDatatypeNull0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiDatatypeNull0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiChar0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiChar0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiUnsignedChar0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiUnsignedChar0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiShort0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiShort0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiUnsignedShort0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiUnsignedShort0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiInt0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiInt0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiUnsigned0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiUnsigned0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiLong0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiLong0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiUnsignedLong0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiUnsignedLong0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiLongLong0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiLongLong0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiFloat0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiFloat0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiDouble0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiDouble0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiByte0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiByte0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiSignedChar0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiSignedChar0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiUnsignedLongLong0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiUnsignedLongLong0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiInt8T0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiInt8T0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiInt16T0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiInt16T0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiInt32T0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiInt32T0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiInt64T0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiInt64T0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiUint8T0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiUint8T0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiUint16T0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiUint16T0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiUint32T0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiUint32T0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiUint64T0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiUint64T0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiThreadSingle0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_getMpiThreadSingle0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiThreadFunneled0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_getMpiThreadFunneled0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiThreadSerialized0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_getMpiThreadSerialized0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiThreadMultiple0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_getMpiThreadMultiple0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiProcNull0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_getMpiProcNull0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiAnySource0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_getMpiAnySource0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiRoot0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_getMpiRoot0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiAnyTag0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_getMpiAnyTag0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiUndefined0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_getMpiUndefined0
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Get_library_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Get_1library_1version
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Init
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Init
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Initialized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Initialized
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Comm_rank
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Comm_1rank
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Comm_size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Comm_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Finalize
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Finalized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Finalized
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Allgather0
 * Signature: (ZLjava/lang/Object;IIJILjava/lang/Object;IIJIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Allgather0
  (JNIEnv *, jclass, jboolean, jobject, jint, jint, jlong, jint, jobject, jint, jint, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Allgather1
 * Signature: (ZJIJJIJJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Allgather1
  (JNIEnv *, jclass, jboolean, jlong, jint, jlong, jlong, jint, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Allgatherv0
 * Signature: (ZLjava/lang/Object;IIJILjava/lang/Object;I[IJIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Allgatherv0
  (JNIEnv *, jclass, jboolean, jobject, jint, jint, jlong, jint, jobject, jint, jintArray, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Allgatherv1
 * Signature: (ZJIJJ[IJJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Allgatherv1
  (JNIEnv *, jclass, jboolean, jlong, jint, jlong, jlong, jintArray, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Allreduce0
 * Signature: (ZLjava/lang/Object;ILjava/lang/Object;IIJIJJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Allreduce0
  (JNIEnv *, jclass, jboolean, jobject, jint, jobject, jint, jint, jlong, jint, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Allreduce1
 * Signature: (ZJJIJJJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Allreduce1
  (JNIEnv *, jclass, jboolean, jlong, jlong, jint, jlong, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_AllreduceB
 * Signature: (BJJ)B
 */
JNIEXPORT jbyte JNICALL Java_jse_parallel_MPI_00024Native_MPI_1AllreduceB
  (JNIEnv *, jclass, jbyte, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_AllreduceD
 * Signature: (DJJ)D
 */
JNIEXPORT jdouble JNICALL Java_jse_parallel_MPI_00024Native_MPI_1AllreduceD
  (JNIEnv *, jclass, jdouble, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_AllreduceZ
 * Signature: (ZJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_parallel_MPI_00024Native_MPI_1AllreduceZ
  (JNIEnv *, jclass, jboolean, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_AllreduceC
 * Signature: (CJJ)C
 */
JNIEXPORT jchar JNICALL Java_jse_parallel_MPI_00024Native_MPI_1AllreduceC
  (JNIEnv *, jclass, jchar, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_AllreduceS
 * Signature: (SJJ)S
 */
JNIEXPORT jshort JNICALL Java_jse_parallel_MPI_00024Native_MPI_1AllreduceS
  (JNIEnv *, jclass, jshort, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_AllreduceI
 * Signature: (IJJ)I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_MPI_1AllreduceI
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_AllreduceL
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1AllreduceL
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_AllreduceF
 * Signature: (FJJ)F
 */
JNIEXPORT jfloat JNICALL Java_jse_parallel_MPI_00024Native_MPI_1AllreduceF
  (JNIEnv *, jclass, jfloat, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Barrier
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Barrier
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Bcast0
 * Signature: (Ljava/lang/Object;IIJIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Bcast0
  (JNIEnv *, jclass, jobject, jint, jint, jlong, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Bcast1
 * Signature: (JIJIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Bcast1
  (JNIEnv *, jclass, jlong, jint, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_BcastB
 * Signature: (BIJ)B
 */
JNIEXPORT jbyte JNICALL Java_jse_parallel_MPI_00024Native_MPI_1BcastB
  (JNIEnv *, jclass, jbyte, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_BcastD
 * Signature: (DIJ)D
 */
JNIEXPORT jdouble JNICALL Java_jse_parallel_MPI_00024Native_MPI_1BcastD
  (JNIEnv *, jclass, jdouble, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_BcastZ
 * Signature: (ZIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_parallel_MPI_00024Native_MPI_1BcastZ
  (JNIEnv *, jclass, jboolean, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_BcastC
 * Signature: (CIJ)C
 */
JNIEXPORT jchar JNICALL Java_jse_parallel_MPI_00024Native_MPI_1BcastC
  (JNIEnv *, jclass, jchar, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_BcastS
 * Signature: (SIJ)S
 */
JNIEXPORT jshort JNICALL Java_jse_parallel_MPI_00024Native_MPI_1BcastS
  (JNIEnv *, jclass, jshort, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_BcastI
 * Signature: (IIJ)I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_MPI_1BcastI
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_BcastL
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1BcastL
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_BcastF
 * Signature: (FIJ)F
 */
JNIEXPORT jfloat JNICALL Java_jse_parallel_MPI_00024Native_MPI_1BcastF
  (JNIEnv *, jclass, jfloat, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Gather0
 * Signature: (ZLjava/lang/Object;IIJILjava/lang/Object;IIJIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Gather0
  (JNIEnv *, jclass, jboolean, jobject, jint, jint, jlong, jint, jobject, jint, jint, jlong, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Gather1
 * Signature: (ZJIJJIJIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Gather1
  (JNIEnv *, jclass, jboolean, jlong, jint, jlong, jlong, jint, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Gatherv0
 * Signature: (ZLjava/lang/Object;IIJILjava/lang/Object;I[IJIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Gatherv0
  (JNIEnv *, jclass, jboolean, jobject, jint, jint, jlong, jint, jobject, jint, jintArray, jlong, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Gatherv1
 * Signature: (ZJIJJ[IJIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Gatherv1
  (JNIEnv *, jclass, jboolean, jlong, jint, jlong, jlong, jintArray, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Reduce0
 * Signature: (ZLjava/lang/Object;ILjava/lang/Object;IIJIJIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Reduce0
  (JNIEnv *, jclass, jboolean, jobject, jint, jobject, jint, jint, jlong, jint, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Reduce1
 * Signature: (ZJJIJJIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Reduce1
  (JNIEnv *, jclass, jboolean, jlong, jlong, jint, jlong, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_ReduceB
 * Signature: (BJIJ)B
 */
JNIEXPORT jbyte JNICALL Java_jse_parallel_MPI_00024Native_MPI_1ReduceB
  (JNIEnv *, jclass, jbyte, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_ReduceD
 * Signature: (DJIJ)D
 */
JNIEXPORT jdouble JNICALL Java_jse_parallel_MPI_00024Native_MPI_1ReduceD
  (JNIEnv *, jclass, jdouble, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_ReduceZ
 * Signature: (ZJIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_parallel_MPI_00024Native_MPI_1ReduceZ
  (JNIEnv *, jclass, jboolean, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_ReduceC
 * Signature: (CJIJ)C
 */
JNIEXPORT jchar JNICALL Java_jse_parallel_MPI_00024Native_MPI_1ReduceC
  (JNIEnv *, jclass, jchar, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_ReduceS
 * Signature: (SJIJ)S
 */
JNIEXPORT jshort JNICALL Java_jse_parallel_MPI_00024Native_MPI_1ReduceS
  (JNIEnv *, jclass, jshort, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_ReduceI
 * Signature: (IJIJ)I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_MPI_1ReduceI
  (JNIEnv *, jclass, jint, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_ReduceL
 * Signature: (JJIJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1ReduceL
  (JNIEnv *, jclass, jlong, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_ReduceF
 * Signature: (FJIJ)F
 */
JNIEXPORT jfloat JNICALL Java_jse_parallel_MPI_00024Native_MPI_1ReduceF
  (JNIEnv *, jclass, jfloat, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Scatter0
 * Signature: (ZLjava/lang/Object;IIJILjava/lang/Object;IIJIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Scatter0
  (JNIEnv *, jclass, jboolean, jobject, jint, jint, jlong, jint, jobject, jint, jint, jlong, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Scatter1
 * Signature: (ZJIJJIJIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Scatter1
  (JNIEnv *, jclass, jboolean, jlong, jint, jlong, jlong, jint, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Scatterv0
 * Signature: (ZLjava/lang/Object;I[IJILjava/lang/Object;IIJIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Scatterv0
  (JNIEnv *, jclass, jboolean, jobject, jint, jintArray, jlong, jint, jobject, jint, jint, jlong, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Scatterv1
 * Signature: (ZJ[IJJIJIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Scatterv1
  (JNIEnv *, jclass, jboolean, jlong, jintArray, jlong, jlong, jint, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Comm_create
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Comm_1create
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Comm_dup
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Comm_1dup
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Comm_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Comm_1free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Comm_split
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Comm_1split
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Comm_group
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Comm_1group
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Group_difference
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Group_1difference
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Group_excl
 * Signature: (JI[I)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Group_1excl
  (JNIEnv *, jclass, jlong, jint, jintArray);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Group_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Group_1free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Group_incl
 * Signature: (JI[I)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Group_1incl
  (JNIEnv *, jclass, jlong, jint, jintArray);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Group_intersection
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Group_1intersection
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Group_rank
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Group_1rank
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Group_size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Group_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Group_union
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Group_1union
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Send0
 * Signature: (Ljava/lang/Object;IIJIIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Send0
  (JNIEnv *, jclass, jobject, jint, jint, jlong, jint, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Send1
 * Signature: (JIJIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Send1
  (JNIEnv *, jclass, jlong, jint, jlong, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_SendB
 * Signature: (BIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1SendB
  (JNIEnv *, jclass, jbyte, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_SendD
 * Signature: (DIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1SendD
  (JNIEnv *, jclass, jdouble, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_SendZ
 * Signature: (ZIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1SendZ
  (JNIEnv *, jclass, jboolean, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_SendC
 * Signature: (CIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1SendC
  (JNIEnv *, jclass, jchar, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_SendS
 * Signature: (SIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1SendS
  (JNIEnv *, jclass, jshort, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_SendI
 * Signature: (IIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1SendI
  (JNIEnv *, jclass, jint, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_SendL
 * Signature: (JIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1SendL
  (JNIEnv *, jclass, jlong, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_SendF
 * Signature: (FIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1SendF
  (JNIEnv *, jclass, jfloat, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Recv0
 * Signature: (Ljava/lang/Object;IIJIIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Recv0
  (JNIEnv *, jclass, jobject, jint, jint, jlong, jint, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Recv1
 * Signature: (JIJIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Recv1
  (JNIEnv *, jclass, jlong, jint, jlong, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_RecvB
 * Signature: (IIJ)B
 */
JNIEXPORT jbyte JNICALL Java_jse_parallel_MPI_00024Native_MPI_1RecvB
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_RecvD
 * Signature: (IIJ)D
 */
JNIEXPORT jdouble JNICALL Java_jse_parallel_MPI_00024Native_MPI_1RecvD
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_RecvZ
 * Signature: (IIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_parallel_MPI_00024Native_MPI_1RecvZ
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_RecvC
 * Signature: (IIJ)C
 */
JNIEXPORT jchar JNICALL Java_jse_parallel_MPI_00024Native_MPI_1RecvC
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_RecvS
 * Signature: (IIJ)S
 */
JNIEXPORT jshort JNICALL Java_jse_parallel_MPI_00024Native_MPI_1RecvS
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_RecvI
 * Signature: (IIJ)I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_MPI_1RecvI
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_RecvL
 * Signature: (IIJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1RecvL
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_RecvF
 * Signature: (IIJ)F
 */
JNIEXPORT jfloat JNICALL Java_jse_parallel_MPI_00024Native_MPI_1RecvF
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Sendrecv0
 * Signature: (Ljava/lang/Object;IIJIIILjava/lang/Object;IIJIIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Sendrecv0
  (JNIEnv *, jclass, jobject, jint, jint, jlong, jint, jint, jint, jobject, jint, jint, jlong, jint, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Sendrecv1
 * Signature: (JIJIIJIJIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Sendrecv1
  (JNIEnv *, jclass, jlong, jint, jlong, jint, jint, jlong, jint, jlong, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Init_thread
 * Signature: ([Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Init_1thread
  (JNIEnv *, jclass, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
