/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_parallel_MPI_Native */

#ifndef _Included_jse_parallel_MPI_Native
#define _Included_jse_parallel_MPI_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiGroupNull_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiGroupNull_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiGroupEmpty_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiGroupEmpty_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiCommNull_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiCommNull_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiCommWorld_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiCommWorld_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiCommSelf_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiCommSelf_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiOpNull_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiOpNull_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiMax_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiMax_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiMin_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiMin_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiSum_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiSum_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiProd_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiProd_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiLand_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiLand_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiBand_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiBand_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiLor_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiLor_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiBor_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiBor_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiLxor_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiLxor_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiBxor_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiBxor_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiMinloc_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiMinloc_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiMaxloc_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiMaxloc_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiReplace_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiReplace_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiDatatypeNull_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiDatatypeNull_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiChar_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiChar_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiUnsignedChar_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiUnsignedChar_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiShort_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiShort_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiUnsignedShort_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiUnsignedShort_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiInt_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiInt_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiUnsigned_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiUnsigned_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiLong_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiLong_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiUnsignedLong_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiUnsignedLong_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiLongLong_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiLongLong_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiFloat_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiFloat_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiDouble_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiDouble_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiByte_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiByte_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiSignedChar_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiSignedChar_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiUnsignedLongLong_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiUnsignedLongLong_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiInt8T_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiInt8T_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiInt16T_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiInt16T_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiInt32T_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiInt32T_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiInt64T_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiInt64T_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiUint8T_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiUint8T_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiUint16T_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiUint16T_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiUint32T_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiUint32T_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiUint64T_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_getMpiUint64T_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiThreadSingle_
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_getMpiThreadSingle_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiThreadFunneled_
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_getMpiThreadFunneled_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiThreadSerialized_
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_getMpiThreadSerialized_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiThreadMultiple_
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_getMpiThreadMultiple_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiProcNull_
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_getMpiProcNull_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiAnySource_
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_getMpiAnySource_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiRoot_
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_getMpiRoot_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiAnyTag_
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_getMpiAnyTag_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    getMpiUndefined_
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_getMpiUndefined_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Get_library_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Get_1library_1version
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Init
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Init
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Initialized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Initialized
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Comm_rank
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Comm_1rank
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Comm_size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Comm_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Finalize
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Finalized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Finalized
  (JNIEnv *, jclass);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Allgather0
 * Signature: (ZLjava/lang/Object;IJILjava/lang/Object;IJIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Allgather0
  (JNIEnv *, jclass, jboolean, jobject, jint, jlong, jint, jobject, jint, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Allgather1
 * Signature: (ZJIJJIJJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Allgather1
  (JNIEnv *, jclass, jboolean, jlong, jint, jlong, jlong, jint, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Allgatherv0
 * Signature: (ZLjava/lang/Object;IJILjava/lang/Object;[I[IJIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Allgatherv0
  (JNIEnv *, jclass, jboolean, jobject, jint, jlong, jint, jobject, jintArray, jintArray, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Allgatherv1
 * Signature: (ZJIJJJJJJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Allgatherv1
  (JNIEnv *, jclass, jboolean, jlong, jint, jlong, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Allreduce0
 * Signature: (ZLjava/lang/Object;Ljava/lang/Object;IJIJJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Allreduce0
  (JNIEnv *, jclass, jboolean, jobject, jobject, jint, jlong, jint, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Allreduce1
 * Signature: (ZJJIJJJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Allreduce1
  (JNIEnv *, jclass, jboolean, jlong, jlong, jint, jlong, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_AllreduceB
 * Signature: (BJJ)B
 */
JNIEXPORT jbyte JNICALL Java_jse_parallel_MPI_00024Native_MPI_1AllreduceB
  (JNIEnv *, jclass, jbyte, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_AllreduceD
 * Signature: (DJJ)D
 */
JNIEXPORT jdouble JNICALL Java_jse_parallel_MPI_00024Native_MPI_1AllreduceD
  (JNIEnv *, jclass, jdouble, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_AllreduceZ
 * Signature: (ZJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_parallel_MPI_00024Native_MPI_1AllreduceZ
  (JNIEnv *, jclass, jboolean, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_AllreduceC
 * Signature: (CJJ)C
 */
JNIEXPORT jchar JNICALL Java_jse_parallel_MPI_00024Native_MPI_1AllreduceC
  (JNIEnv *, jclass, jchar, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_AllreduceS
 * Signature: (SJJ)S
 */
JNIEXPORT jshort JNICALL Java_jse_parallel_MPI_00024Native_MPI_1AllreduceS
  (JNIEnv *, jclass, jshort, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_AllreduceI
 * Signature: (IJJ)I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_MPI_1AllreduceI
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_AllreduceL
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1AllreduceL
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_AllreduceF
 * Signature: (FJJ)F
 */
JNIEXPORT jfloat JNICALL Java_jse_parallel_MPI_00024Native_MPI_1AllreduceF
  (JNIEnv *, jclass, jfloat, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Barrier
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Barrier
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Bcast0
 * Signature: (Ljava/lang/Object;IJIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Bcast0
  (JNIEnv *, jclass, jobject, jint, jlong, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Bcast1
 * Signature: (JIJIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Bcast1
  (JNIEnv *, jclass, jlong, jint, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_BcastB
 * Signature: (BIJ)B
 */
JNIEXPORT jbyte JNICALL Java_jse_parallel_MPI_00024Native_MPI_1BcastB
  (JNIEnv *, jclass, jbyte, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_BcastD
 * Signature: (DIJ)D
 */
JNIEXPORT jdouble JNICALL Java_jse_parallel_MPI_00024Native_MPI_1BcastD
  (JNIEnv *, jclass, jdouble, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_BcastZ
 * Signature: (ZIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_parallel_MPI_00024Native_MPI_1BcastZ
  (JNIEnv *, jclass, jboolean, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_BcastC
 * Signature: (CIJ)C
 */
JNIEXPORT jchar JNICALL Java_jse_parallel_MPI_00024Native_MPI_1BcastC
  (JNIEnv *, jclass, jchar, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_BcastS
 * Signature: (SIJ)S
 */
JNIEXPORT jshort JNICALL Java_jse_parallel_MPI_00024Native_MPI_1BcastS
  (JNIEnv *, jclass, jshort, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_BcastI
 * Signature: (IIJ)I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_MPI_1BcastI
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_BcastL
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1BcastL
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_BcastF
 * Signature: (FIJ)F
 */
JNIEXPORT jfloat JNICALL Java_jse_parallel_MPI_00024Native_MPI_1BcastF
  (JNIEnv *, jclass, jfloat, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Gather0
 * Signature: (ZLjava/lang/Object;IJILjava/lang/Object;IJIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Gather0
  (JNIEnv *, jclass, jboolean, jobject, jint, jlong, jint, jobject, jint, jlong, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Gather1
 * Signature: (ZJIJJIJIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Gather1
  (JNIEnv *, jclass, jboolean, jlong, jint, jlong, jlong, jint, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Gatherv0
 * Signature: (ZLjava/lang/Object;IJILjava/lang/Object;[I[IJIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Gatherv0
  (JNIEnv *, jclass, jboolean, jobject, jint, jlong, jint, jobject, jintArray, jintArray, jlong, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Gatherv1
 * Signature: (ZJIJJJJJIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Gatherv1
  (JNIEnv *, jclass, jboolean, jlong, jint, jlong, jlong, jlong, jlong, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Reduce0
 * Signature: (ZLjava/lang/Object;Ljava/lang/Object;IJIJIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Reduce0
  (JNIEnv *, jclass, jboolean, jobject, jobject, jint, jlong, jint, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Reduce1
 * Signature: (ZJJIJJIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Reduce1
  (JNIEnv *, jclass, jboolean, jlong, jlong, jint, jlong, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_ReduceB
 * Signature: (BJIJ)B
 */
JNIEXPORT jbyte JNICALL Java_jse_parallel_MPI_00024Native_MPI_1ReduceB
  (JNIEnv *, jclass, jbyte, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_ReduceD
 * Signature: (DJIJ)D
 */
JNIEXPORT jdouble JNICALL Java_jse_parallel_MPI_00024Native_MPI_1ReduceD
  (JNIEnv *, jclass, jdouble, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_ReduceZ
 * Signature: (ZJIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_parallel_MPI_00024Native_MPI_1ReduceZ
  (JNIEnv *, jclass, jboolean, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_ReduceC
 * Signature: (CJIJ)C
 */
JNIEXPORT jchar JNICALL Java_jse_parallel_MPI_00024Native_MPI_1ReduceC
  (JNIEnv *, jclass, jchar, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_ReduceS
 * Signature: (SJIJ)S
 */
JNIEXPORT jshort JNICALL Java_jse_parallel_MPI_00024Native_MPI_1ReduceS
  (JNIEnv *, jclass, jshort, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_ReduceI
 * Signature: (IJIJ)I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_MPI_1ReduceI
  (JNIEnv *, jclass, jint, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_ReduceL
 * Signature: (JJIJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1ReduceL
  (JNIEnv *, jclass, jlong, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_ReduceF
 * Signature: (FJIJ)F
 */
JNIEXPORT jfloat JNICALL Java_jse_parallel_MPI_00024Native_MPI_1ReduceF
  (JNIEnv *, jclass, jfloat, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Scatter0
 * Signature: (ZLjava/lang/Object;IJILjava/lang/Object;IJIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Scatter0
  (JNIEnv *, jclass, jboolean, jobject, jint, jlong, jint, jobject, jint, jlong, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Scatter1
 * Signature: (ZJIJJIJIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Scatter1
  (JNIEnv *, jclass, jboolean, jlong, jint, jlong, jlong, jint, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Scatterv0
 * Signature: (ZLjava/lang/Object;[I[IJILjava/lang/Object;IJIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Scatterv0
  (JNIEnv *, jclass, jboolean, jobject, jintArray, jintArray, jlong, jint, jobject, jint, jlong, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Scatterv1
 * Signature: (ZJJJJJIJIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Scatterv1
  (JNIEnv *, jclass, jboolean, jlong, jlong, jlong, jlong, jlong, jint, jlong, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Comm_create
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Comm_1create
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Comm_dup
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Comm_1dup
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Comm_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Comm_1free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Comm_split
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Comm_1split
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Comm_group
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Comm_1group
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Group_difference
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Group_1difference
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Group_excl
 * Signature: (JI[I)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Group_1excl
  (JNIEnv *, jclass, jlong, jint, jintArray);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Group_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Group_1free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Group_incl
 * Signature: (JI[I)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Group_1incl
  (JNIEnv *, jclass, jlong, jint, jintArray);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Group_intersection
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Group_1intersection
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Group_rank
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Group_1rank
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Group_size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Group_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Group_union
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Group_1union
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Send0
 * Signature: (Ljava/lang/Object;IJIIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Send0
  (JNIEnv *, jclass, jobject, jint, jlong, jint, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Send1
 * Signature: (JIJIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Send1
  (JNIEnv *, jclass, jlong, jint, jlong, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_SendB
 * Signature: (BIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1SendB
  (JNIEnv *, jclass, jbyte, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_SendD
 * Signature: (DIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1SendD
  (JNIEnv *, jclass, jdouble, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_SendZ
 * Signature: (ZIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1SendZ
  (JNIEnv *, jclass, jboolean, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_SendC
 * Signature: (CIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1SendC
  (JNIEnv *, jclass, jchar, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_SendS
 * Signature: (SIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1SendS
  (JNIEnv *, jclass, jshort, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_SendI
 * Signature: (IIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1SendI
  (JNIEnv *, jclass, jint, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_SendL
 * Signature: (JIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1SendL
  (JNIEnv *, jclass, jlong, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_SendF
 * Signature: (FIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1SendF
  (JNIEnv *, jclass, jfloat, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Recv0
 * Signature: (Ljava/lang/Object;IJIIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Recv0
  (JNIEnv *, jclass, jobject, jint, jlong, jint, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Recv1
 * Signature: (JIJIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Recv1
  (JNIEnv *, jclass, jlong, jint, jlong, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_RecvB
 * Signature: (IIJ)B
 */
JNIEXPORT jbyte JNICALL Java_jse_parallel_MPI_00024Native_MPI_1RecvB
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_RecvD
 * Signature: (IIJ)D
 */
JNIEXPORT jdouble JNICALL Java_jse_parallel_MPI_00024Native_MPI_1RecvD
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_RecvZ
 * Signature: (IIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_parallel_MPI_00024Native_MPI_1RecvZ
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_RecvC
 * Signature: (IIJ)C
 */
JNIEXPORT jchar JNICALL Java_jse_parallel_MPI_00024Native_MPI_1RecvC
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_RecvS
 * Signature: (IIJ)S
 */
JNIEXPORT jshort JNICALL Java_jse_parallel_MPI_00024Native_MPI_1RecvS
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_RecvI
 * Signature: (IIJ)I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_MPI_1RecvI
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_RecvL
 * Signature: (IIJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_parallel_MPI_00024Native_MPI_1RecvL
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_RecvF
 * Signature: (IIJ)F
 */
JNIEXPORT jfloat JNICALL Java_jse_parallel_MPI_00024Native_MPI_1RecvF
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Sendrecv0
 * Signature: (Ljava/lang/Object;IJIIILjava/lang/Object;IJIIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Sendrecv0
  (JNIEnv *, jclass, jobject, jint, jlong, jint, jint, jint, jobject, jint, jlong, jint, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Sendrecv1
 * Signature: (JIJIIJIJIIJ)V
 */
JNIEXPORT void JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Sendrecv1
  (JNIEnv *, jclass, jlong, jint, jlong, jint, jint, jlong, jint, jlong, jint, jint, jlong);

/*
 * Class:     jse_parallel_MPI_Native
 * Method:    MPI_Init_thread
 * Signature: ([Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_jse_parallel_MPI_00024Native_MPI_1Init_1thread
  (JNIEnv *, jclass, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
