/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jtool_parallel_MPI_Native */

#ifndef _Included_jtool_parallel_MPI_Native
#define _Included_jtool_parallel_MPI_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiCommNull_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiCommNull_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiCommWorld_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiCommWorld_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiCommSelf_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiCommSelf_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiOpNull_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiOpNull_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiMax_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiMax_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiMin_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiMin_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiSum_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiSum_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiProd_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiProd_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiLand_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiLand_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiBand_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiBand_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiLor_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiLor_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiBor_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiBor_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiLxor_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiLxor_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiBxor_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiBxor_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiMinloc_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiMinloc_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiMaxloc_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiMaxloc_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiReplace_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiReplace_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiDatatypeNull_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiDatatypeNull_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiChar_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiChar_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiUnsignedChar_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiUnsignedChar_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiShort_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiShort_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiUnsignedShort_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiUnsignedShort_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiInt_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiInt_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiUnsigned_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiUnsigned_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiLong_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiLong_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiUnsignedLong_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiUnsignedLong_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiLongLong_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiLongLong_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiFloat_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiFloat_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiDouble_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiDouble_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiByte_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiByte_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiSignedChar_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiSignedChar_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiUnsignedLongLong_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiUnsignedLongLong_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiInt8T_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiInt8T_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiInt16T_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiInt16T_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiInt32T_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiInt32T_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiInt64T_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiInt64T_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiUint8T_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiUint8T_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiUint16T_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiUint16T_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiUint32T_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiUint32T_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiUint64T_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jtool_parallel_MPI_00024Native_getMpiUint64T_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiThreadSingle_
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jtool_parallel_MPI_00024Native_getMpiThreadSingle_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiThreadFunneled_
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jtool_parallel_MPI_00024Native_getMpiThreadFunneled_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiThreadSerialized_
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jtool_parallel_MPI_00024Native_getMpiThreadSerialized_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiThreadMultiple_
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jtool_parallel_MPI_00024Native_getMpiThreadMultiple_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiProcNull_
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jtool_parallel_MPI_00024Native_getMpiProcNull_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiAnySource_
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jtool_parallel_MPI_00024Native_getMpiAnySource_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiRoot_
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jtool_parallel_MPI_00024Native_getMpiRoot_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    getMpiAnyTag_
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jtool_parallel_MPI_00024Native_getMpiAnyTag_1
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    MPI_Init
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jtool_parallel_MPI_00024Native_MPI_1Init
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    MPI_Initialized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jtool_parallel_MPI_00024Native_MPI_1Initialized
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    MPI_Comm_rank
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jtool_parallel_MPI_00024Native_MPI_1Comm_1rank
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    MPI_Comm_size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jtool_parallel_MPI_00024Native_MPI_1Comm_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    MPI_Finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jtool_parallel_MPI_00024Native_MPI_1Finalize
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    MPI_Finalized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jtool_parallel_MPI_00024Native_MPI_1Finalized
  (JNIEnv *, jclass);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    MPI_Allgather0
 * Signature: (ZLjava/lang/Object;IJLjava/lang/Object;IJJ)V
 */
JNIEXPORT void JNICALL Java_jtool_parallel_MPI_00024Native_MPI_1Allgather0
  (JNIEnv *, jclass, jboolean, jobject, jint, jlong, jobject, jint, jlong, jlong);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    MPI_Allgatherv0
 * Signature: (ZLjava/lang/Object;IJLjava/lang/Object;[I[IJJ)V
 */
JNIEXPORT void JNICALL Java_jtool_parallel_MPI_00024Native_MPI_1Allgatherv0
  (JNIEnv *, jclass, jboolean, jobject, jint, jlong, jobject, jintArray, jintArray, jlong, jlong);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    MPI_Allreduce0
 * Signature: (ZLjava/lang/Object;Ljava/lang/Object;IJJJ)V
 */
JNIEXPORT void JNICALL Java_jtool_parallel_MPI_00024Native_MPI_1Allreduce0
  (JNIEnv *, jclass, jboolean, jobject, jobject, jint, jlong, jlong, jlong);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    MPI_Bcast0
 * Signature: (Ljava/lang/Object;IJIJ)V
 */
JNIEXPORT void JNICALL Java_jtool_parallel_MPI_00024Native_MPI_1Bcast0
  (JNIEnv *, jclass, jobject, jint, jlong, jint, jlong);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    MPI_Gather0
 * Signature: (ZLjava/lang/Object;IJLjava/lang/Object;IJIJ)V
 */
JNIEXPORT void JNICALL Java_jtool_parallel_MPI_00024Native_MPI_1Gather0
  (JNIEnv *, jclass, jboolean, jobject, jint, jlong, jobject, jint, jlong, jint, jlong);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    MPI_Gatherv0
 * Signature: (ZLjava/lang/Object;IJLjava/lang/Object;[I[IJIJ)V
 */
JNIEXPORT void JNICALL Java_jtool_parallel_MPI_00024Native_MPI_1Gatherv0
  (JNIEnv *, jclass, jboolean, jobject, jint, jlong, jobject, jintArray, jintArray, jlong, jint, jlong);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    MPI_Reduce0
 * Signature: (ZLjava/lang/Object;Ljava/lang/Object;IJJIJ)V
 */
JNIEXPORT void JNICALL Java_jtool_parallel_MPI_00024Native_MPI_1Reduce0
  (JNIEnv *, jclass, jboolean, jobject, jobject, jint, jlong, jlong, jint, jlong);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    MPI_Send0
 * Signature: (Ljava/lang/Object;IJIIJ)V
 */
JNIEXPORT void JNICALL Java_jtool_parallel_MPI_00024Native_MPI_1Send0
  (JNIEnv *, jclass, jobject, jint, jlong, jint, jint, jlong);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    MPI_Recv0
 * Signature: (Ljava/lang/Object;IJIIJ)V
 */
JNIEXPORT void JNICALL Java_jtool_parallel_MPI_00024Native_MPI_1Recv0
  (JNIEnv *, jclass, jobject, jint, jlong, jint, jint, jlong);

/*
 * Class:     jtool_parallel_MPI_Native
 * Method:    MPI_Init_thread
 * Signature: ([Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_jtool_parallel_MPI_00024Native_MPI_1Init_1thread
  (JNIEnv *, jclass, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
