/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_lmp_NativeLmpPointer */

#ifndef _Included_jse_lmp_NativeLmpPointer
#define _Included_jse_lmp_NativeLmpPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_lmp_NativeLmpPointer
 * Method:    lammpsClose0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmpPointer_lammpsClose0
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
