/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_lmp_NativeLmp */

#ifndef _Included_jse_lmp_NativeLmp
#define _Included_jse_lmp_NativeLmp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsOpen_
 * Signature: ([Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_NativeLmp_lammpsOpen_1___3Ljava_lang_String_2J
  (JNIEnv *, jclass, jobjectArray, jlong);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsOpen_
 * Signature: ([Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_NativeLmp_lammpsOpen_1___3Ljava_lang_String_2
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsVersion_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_NativeLmp_lammpsVersion_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsComm_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_NativeLmp_lammpsComm_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsFile_
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsFile_1
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsCommand_
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsCommand_1
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsCommandsList_
 * Signature: (J[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsCommandsList_1
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsCommandsString_
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsCommandsString_1
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsGetNatoms_
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_NativeLmp_lammpsGetNatoms_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractBox_
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsExtractBox_1
  (JNIEnv *, jclass, jlong, jdoubleArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsResetBox_
 * Signature: (JDDDDDDDDD)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsResetBox_1
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsGetThermo_
 * Signature: (JLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_NativeLmp_lammpsGetThermo_1
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractSetting_
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_NativeLmp_lammpsExtractSetting_1
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsGatherConcat_
 * Signature: (JLjava/lang/String;ZI[D)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsGatherConcat_1
  (JNIEnv *, jclass, jlong, jstring, jboolean, jint, jdoubleArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsGatherConcatInt_
 * Signature: (JLjava/lang/String;I[I)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsGatherConcatInt_1
  (JNIEnv *, jclass, jlong, jstring, jint, jintArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractAtom_
 * Signature: (JLjava/lang/String;III[D)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsExtractAtom_1
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint, jdoubleArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractAtomInt_
 * Signature: (JLjava/lang/String;III[I)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsExtractAtomInt_1
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint, jintArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractAtomLong_
 * Signature: (JLjava/lang/String;III[J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsExtractAtomLong_1
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint, jlongArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsScatter_
 * Signature: (JLjava/lang/String;ZII[D)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsScatter_1
  (JNIEnv *, jclass, jlong, jstring, jboolean, jint, jint, jdoubleArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsCreateAtoms_
 * Signature: (JI[I[I[D[D[IZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsCreateAtoms_1
  (JNIEnv *, jclass, jlong, jint, jintArray, jintArray, jdoubleArray, jdoubleArray, jintArray, jboolean);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsClose_
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsClose_1
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
