/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_lmp_NativeLmp */

#ifndef _Included_jse_lmp_NativeLmp
#define _Included_jse_lmp_NativeLmp
#ifdef __cplusplus
extern "C" {
#endif
#undef jse_lmp_NativeLmp_LMP_STYLE_GLOBAL
#define jse_lmp_NativeLmp_LMP_STYLE_GLOBAL 0L
#undef jse_lmp_NativeLmp_LMP_STYLE_ATOM
#define jse_lmp_NativeLmp_LMP_STYLE_ATOM 1L
#undef jse_lmp_NativeLmp_LMP_STYLE_LOCAL
#define jse_lmp_NativeLmp_LMP_STYLE_LOCAL 2L
#undef jse_lmp_NativeLmp_LMP_TYPE_SCALAR
#define jse_lmp_NativeLmp_LMP_TYPE_SCALAR 0L
#undef jse_lmp_NativeLmp_LMP_TYPE_VECTOR
#define jse_lmp_NativeLmp_LMP_TYPE_VECTOR 1L
#undef jse_lmp_NativeLmp_LMP_TYPE_ARRAY
#define jse_lmp_NativeLmp_LMP_TYPE_ARRAY 2L
#undef jse_lmp_NativeLmp_LMP_SIZE_VECTOR
#define jse_lmp_NativeLmp_LMP_SIZE_VECTOR 3L
#undef jse_lmp_NativeLmp_LMP_SIZE_ROWS
#define jse_lmp_NativeLmp_LMP_SIZE_ROWS 4L
#undef jse_lmp_NativeLmp_LMP_SIZE_COLS
#define jse_lmp_NativeLmp_LMP_SIZE_COLS 5L
/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsOpen0
 * Signature: ([Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_NativeLmp_lammpsOpen0
  (JNIEnv *, jclass, jobjectArray, jlong);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsOpen1
 * Signature: ([Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_NativeLmp_lammpsOpen1
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsHasStyle0
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_NativeLmp_lammpsHasStyle0
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsVersion0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_NativeLmp_lammpsVersion0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsVersionStr0
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jse_lmp_NativeLmp_lammpsVersionStr0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsComm0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_NativeLmp_lammpsComm0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsLibMpi0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_NativeLmp_lammpsLibMpi0
  (JNIEnv *, jclass);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsBigbig0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_NativeLmp_lammpsBigbig0
  (JNIEnv *, jclass);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsMpiInit0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsMpiInit0
  (JNIEnv *, jclass);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsMpiFinalize0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsMpiFinalize0
  (JNIEnv *, jclass);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsKokkosFinalize0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsKokkosFinalize0
  (JNIEnv *, jclass);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsPluginFinalize0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsPluginFinalize0
  (JNIEnv *, jclass);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsPythonFinalize0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsPythonFinalize0
  (JNIEnv *, jclass);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsFile0
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsFile0
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsInputFile0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsInputFile0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsCommand0
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsCommand0
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsCommandsList0
 * Signature: (J[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsCommandsList0
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsCommandsString0
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsCommandsString0
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsGetNatoms0
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_NativeLmp_lammpsGetNatoms0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractBox0
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsExtractBox0
  (JNIEnv *, jclass, jlong, jdoubleArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsResetBox0
 * Signature: (JDDDDDDDDD)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsResetBox0
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsGetThermo0
 * Signature: (JLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_NativeLmp_lammpsGetThermo0
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractSetting0
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_NativeLmp_lammpsExtractSetting0
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsGatherConcat0
 * Signature: (JLjava/lang/String;ZI[D)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsGatherConcat0
  (JNIEnv *, jclass, jlong, jstring, jboolean, jint, jdoubleArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsGatherConcatInt0
 * Signature: (JLjava/lang/String;I[I)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsGatherConcatInt0
  (JNIEnv *, jclass, jlong, jstring, jint, jintArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractAtom0
 * Signature: (JLjava/lang/String;III[D)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsExtractAtom0
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint, jdoubleArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractAtomInt0
 * Signature: (JLjava/lang/String;III[I)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsExtractAtomInt0
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint, jintArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractAtomLong0
 * Signature: (JLjava/lang/String;III[J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsExtractAtomLong0
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint, jlongArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractAtomCPointer0
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_NativeLmp_lammpsExtractAtomCPointer0
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsGatherCompute0
 * Signature: (JLjava/lang/String;I[D)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsGatherCompute0
  (JNIEnv *, jclass, jlong, jstring, jint, jdoubleArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractCompute0
 * Signature: (JLjava/lang/String;IIII[D)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsExtractCompute0
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint, jint, jdoubleArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractComputeSize0
 * Signature: (JLjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_NativeLmp_lammpsExtractComputeSize0
  (JNIEnv *, jclass, jlong, jstring, jint, jint);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractComputeCPointer0
 * Signature: (JLjava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_NativeLmp_lammpsExtractComputeCPointer0
  (JNIEnv *, jclass, jlong, jstring, jint, jint);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsScatter0
 * Signature: (JLjava/lang/String;ZII[D)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsScatter0
  (JNIEnv *, jclass, jlong, jstring, jboolean, jint, jint, jdoubleArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsCreateAtoms0
 * Signature: (JI[I[I[D[D[IZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsCreateAtoms0
  (JNIEnv *, jclass, jlong, jint, jintArray, jintArray, jdoubleArray, jdoubleArray, jintArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
