/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_lmp_NativeLmp */

#ifndef _Included_jse_lmp_NativeLmp
#define _Included_jse_lmp_NativeLmp
#ifdef __cplusplus
extern "C" {
#endif
#undef jse_lmp_NativeLmp_LMP_STYLE_GLOBAL
#define jse_lmp_NativeLmp_LMP_STYLE_GLOBAL 0L
#undef jse_lmp_NativeLmp_LMP_STYLE_ATOM
#define jse_lmp_NativeLmp_LMP_STYLE_ATOM 1L
#undef jse_lmp_NativeLmp_LMP_STYLE_LOCAL
#define jse_lmp_NativeLmp_LMP_STYLE_LOCAL 2L
#undef jse_lmp_NativeLmp_LMP_TYPE_SCALAR
#define jse_lmp_NativeLmp_LMP_TYPE_SCALAR 0L
#undef jse_lmp_NativeLmp_LMP_TYPE_VECTOR
#define jse_lmp_NativeLmp_LMP_TYPE_VECTOR 1L
#undef jse_lmp_NativeLmp_LMP_TYPE_ARRAY
#define jse_lmp_NativeLmp_LMP_TYPE_ARRAY 2L
#undef jse_lmp_NativeLmp_LMP_SIZE_VECTOR
#define jse_lmp_NativeLmp_LMP_SIZE_VECTOR 3L
#undef jse_lmp_NativeLmp_LMP_SIZE_ROWS
#define jse_lmp_NativeLmp_LMP_SIZE_ROWS 4L
#undef jse_lmp_NativeLmp_LMP_SIZE_COLS
#define jse_lmp_NativeLmp_LMP_SIZE_COLS 5L
/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsOpen_
 * Signature: ([Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_NativeLmp_lammpsOpen_1___3Ljava_lang_String_2J
  (JNIEnv *, jclass, jobjectArray, jlong);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsOpen_
 * Signature: ([Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_NativeLmp_lammpsOpen_1___3Ljava_lang_String_2
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsVersion_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_NativeLmp_lammpsVersion_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsVersionStr_
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jse_lmp_NativeLmp_lammpsVersionStr_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsComm_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_NativeLmp_lammpsComm_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsLibMpi_
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_NativeLmp_lammpsLibMpi_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsBigbig_
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jse_lmp_NativeLmp_lammpsBigbig_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsMpiFinalize_
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsMpiFinalize_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsFile_
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsFile_1
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsInputFile_
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsInputFile_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsCommand_
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsCommand_1
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsCommandsList_
 * Signature: (J[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsCommandsList_1
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsCommandsString_
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsCommandsString_1
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsGetNatoms_
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_NativeLmp_lammpsGetNatoms_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractBox_
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsExtractBox_1
  (JNIEnv *, jclass, jlong, jdoubleArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsResetBox_
 * Signature: (JDDDDDDDDD)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsResetBox_1
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsGetThermo_
 * Signature: (JLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_jse_lmp_NativeLmp_lammpsGetThermo_1
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractSetting_
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_NativeLmp_lammpsExtractSetting_1
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsGatherConcat_
 * Signature: (JLjava/lang/String;ZI[D)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsGatherConcat_1
  (JNIEnv *, jclass, jlong, jstring, jboolean, jint, jdoubleArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsGatherConcatInt_
 * Signature: (JLjava/lang/String;I[I)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsGatherConcatInt_1
  (JNIEnv *, jclass, jlong, jstring, jint, jintArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractAtom_
 * Signature: (JLjava/lang/String;III[D)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsExtractAtom_1
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint, jdoubleArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractAtomInt_
 * Signature: (JLjava/lang/String;III[I)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsExtractAtomInt_1
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint, jintArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractAtomLong_
 * Signature: (JLjava/lang/String;III[J)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsExtractAtomLong_1
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint, jlongArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractAtomCPointer_
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_NativeLmp_lammpsExtractAtomCPointer_1
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsGatherCompute_
 * Signature: (JLjava/lang/String;I[D)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsGatherCompute_1
  (JNIEnv *, jclass, jlong, jstring, jint, jdoubleArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractCompute_
 * Signature: (JLjava/lang/String;IIII[D)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsExtractCompute_1
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint, jint, jdoubleArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractComputeSize_
 * Signature: (JLjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_jse_lmp_NativeLmp_lammpsExtractComputeSize_1
  (JNIEnv *, jclass, jlong, jstring, jint, jint);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsExtractComputeCPointer_
 * Signature: (JLjava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_jse_lmp_NativeLmp_lammpsExtractComputeCPointer_1
  (JNIEnv *, jclass, jlong, jstring, jint, jint);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsScatter_
 * Signature: (JLjava/lang/String;ZII[D)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsScatter_1
  (JNIEnv *, jclass, jlong, jstring, jboolean, jint, jint, jdoubleArray);

/*
 * Class:     jse_lmp_NativeLmp
 * Method:    lammpsCreateAtoms_
 * Signature: (JI[I[I[D[D[IZ)V
 */
JNIEXPORT void JNICALL Java_jse_lmp_NativeLmp_lammpsCreateAtoms_1
  (JNIEnv *, jclass, jlong, jint, jintArray, jintArray, jdoubleArray, jdoubleArray, jintArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
