package jse.gpu;

import jse.clib.NVCC;
import jse.code.IO;
import jse.jit.SimpleJIT;
import org.jetbrains.annotations.ApiStatus;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.util.List;

/**
 * 用于运行时编写 cuda 核函数的工具类，目前采用
 * {@link SimpleJIT} 的简单实现（不依赖 NVRTC）
 * @author liqa
 */
@ApiStatus.Experimental
public class CudaJIT {
    static {
        // 简单依赖 SimpleJIT
        SimpleJIT.InitHelper.init();
    }
    
    public static Engine engine() {return new Engine();}
    
    public static class Engine extends SimpleJIT.Engine {
        private @Nullable String mCmakeCudaCompiler = null, mCmakeCudaFlags = null;
        
        protected Engine() {}
        public Engine setCmakeCudaCompiler(@Nullable String aCmakeCudaCompiler) {
            mCmakeCudaCompiler = aCmakeCudaCompiler;
            return this;
        }
        public Engine setCmakeCudaFlags(@Nullable String aCmakeCudaFlags) {
            mCmakeCudaFlags = aCmakeCudaFlags;
            return this;
        }
        
        @Override protected void preInitCmakeCmd(List<String> rCommand) {
            // 这里设置 cuda 编译器
            if (mCmakeCudaCompiler!=null) {rCommand.add("-D"); rCommand.add("CMAKE_CUDA_COMPILER="+mCmakeCudaCompiler);}
            if (mCmakeCudaFlags!=null) {rCommand.add("-D"); rCommand.add("CMAKE_CUDA_FLAGS='"+mCmakeCudaFlags+"'");}
        }
        @Override protected String srcName() {return "jitsrc.cu";}
        @Override protected void envChecker() throws Exception {
            NVCC.printInfo();
            super.envChecker();
        }
        
        @ApiStatus.Internal
        @Override public void writeCmakeFile(String aSrcDir, String aSrcName) throws IOException {
            IO.write(aSrcDir+"CMakeLists.txt",
                "#####################################################",
                "#  DO NOT EDIT THIS FILE - it is machine generated  #",
                "#####################################################",
                "cmake_minimum_required(VERSION 3.24)",
                "project("+projectName()+" LANGUAGES CXX CUDA)",
                "set(CMAKE_CXX_STANDARD 11)",
                "set(CMAKE_CUDA_STANDARD 11)",
                "set(CMAKE_CXX_STANDARD_REQUIRED ON)",
                "set(CMAKE_CUDA_STANDARD_REQUIRED ON)",
                "",
                "if(MSVC)",
                "    add_compile_options(-Xcompiler \"/wd4819\")",
                "endif()",
                "if(NOT CMAKE_BUILD_TYPE)",
                "    set(CMAKE_BUILD_TYPE Release)",
                "endif()",
                "set(SOURCE_FILES "+aSrcName+")",
                "add_library("+projectName()+" SHARED ${SOURCE_FILES})",
                "",
                "if(CMAKE_SYSTEM_NAME MATCHES \"Windows\")",
                "    set(BUILD_SHARED_LIBS ON)",
                "endif()",
                "set_target_properties("+projectName()+" PROPERTIES",
                "    C_VISIBILITY_PRESET hidden",
                "    CXX_VISIBILITY_PRESET hidden",
                "    CUDA_VISIBILITY_PRESET hidden",
                "    VISIBILITY_INLINES_HIDDEN YES",
                ")",
                "",
                "option(JSE_OPTIM_MAX \"Use the most aggressive optimization settings\" OFF)",
                "option(JSE_OPTIM_BASE \"Use basic optimization settings\" ON)",
                "option(JSE_OPTIM_COMPAT \"Use the most compatible optimization settings\" OFF)",
                "set_target_properties("+projectName()+" PROPERTIES CUDA_SEPARABLE_COMPILATION ON)",
                "if(JSE_OPTIM_MAX)",
                "    set(CMAKE_CUDA_FLAGS \"${CMAKE_CUDA_FLAGS} -O3 --use_fast_math --fmad=true\")",
                "    set_target_properties("+projectName()+" PROPERTIES CUDA_ARCHITECTURES native)",
                "elseif(JSE_OPTIM_BASE)",
                "    set(CMAKE_CUDA_FLAGS \"${CMAKE_CUDA_FLAGS} -O3 --use_fast_math\")",
                "    set_target_properties("+projectName()+" PROPERTIES CUDA_ARCHITECTURES native)",
                "elseif(JSE_OPTIM_COMPAT)",
                "    set(CMAKE_CUDA_FLAGS \"${CMAKE_CUDA_FLAGS} -O3 --use_fast_math\")",
                "endif()"
            );
        }
    }
}
