/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_clib_SimpleJIT */

#ifndef _Included_jse_clib_SimpleJIT
#define _Included_jse_clib_SimpleJIT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_clib_SimpleJIT
 * Method:    loadLibrary0
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jse_clib_SimpleJIT_loadLibrary0
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jse_clib_SimpleJIT
 * Method:    findFunction0
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jse_clib_SimpleJIT_findMethod0
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     jse_clib_SimpleJIT
 * Method:    invokeFunction0
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_jse_clib_SimpleJIT_invokeMethod0
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
