/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_jit_JITLibHandle */

#ifndef _Included_jse_jit_JITLibHandle
#define _Included_jse_jit_JITLibHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_jit_JITLibHandle
 * Method:    freeLibrary0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_jit_JITLibHandle_freeLibrary0
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
