/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsex_nnap_model_TorchModel */

#ifndef _Included_jsex_nnap_model_TorchModel
#define _Included_jsex_nnap_model_TorchModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsex_nnap_model_TorchModel
 * Method:    setSingleThread0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_model_TorchModel_setSingleThread0
  (JNIEnv *, jclass);

/*
 * Class:     jsex_nnap_model_TorchModel
 * Method:    load0
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jsex_nnap_model_TorchModel_load0
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jsex_nnap_model_TorchModel
 * Method:    load1
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_jsex_nnap_model_TorchModel_load1
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     jsex_nnap_model_TorchModel
 * Method:    forward0
 * Signature: (J[DII)D
 */
JNIEXPORT jdouble JNICALL Java_jsex_nnap_model_TorchModel_forward0
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jint);

/*
 * Class:     jsex_nnap_model_TorchModel
 * Method:    forward1
 * Signature: (JJI)D
 */
JNIEXPORT jdouble JNICALL Java_jsex_nnap_model_TorchModel_forward1
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     jsex_nnap_model_TorchModel
 * Method:    batchForward0
 * Signature: (J[DII[DII)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_model_TorchModel_batchForward0
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jint, jdoubleArray, jint, jint);

/*
 * Class:     jsex_nnap_model_TorchModel
 * Method:    batchForward1
 * Signature: (JJIJI)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_model_TorchModel_batchForward1
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jint);

/*
 * Class:     jsex_nnap_model_TorchModel
 * Method:    backward0
 * Signature: (J[DI[DII)D
 */
JNIEXPORT jdouble JNICALL Java_jsex_nnap_model_TorchModel_backward0
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jdoubleArray, jint, jint);

/*
 * Class:     jsex_nnap_model_TorchModel
 * Method:    backward1
 * Signature: (JJJI)D
 */
JNIEXPORT jdouble JNICALL Java_jsex_nnap_model_TorchModel_backward1
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     jsex_nnap_model_TorchModel
 * Method:    batchBackward0
 * Signature: (J[DI[DII[DII)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_model_TorchModel_batchBackward0
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jdoubleArray, jint, jint, jdoubleArray, jint, jint);

/*
 * Class:     jsex_nnap_model_TorchModel
 * Method:    batchBackward1
 * Signature: (JJJIJI)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_model_TorchModel_batchBackward1
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
