/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_math_operation_ARRAY_Native */

#ifndef _Included_jse_math_operation_ARRAY_Native
#define _Included_jse_math_operation_ARRAY_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_math_operation_ARRAY_Native
 * Method:    sumOfThis_
 * Signature: ([DII)D
 */
JNIEXPORT jdouble JNICALL Java_jse_math_operation_ARRAY_00024Native_sumOfThis_1
  (JNIEnv *, jclass, jdoubleArray, jint, jint);

/*
 * Class:     jse_math_operation_ARRAY_Native
 * Method:    prodOfThis_
 * Signature: ([DII)D
 */
JNIEXPORT jdouble JNICALL Java_jse_math_operation_ARRAY_00024Native_prodOfThis_1
  (JNIEnv *, jclass, jdoubleArray, jint, jint);

/*
 * Class:     jse_math_operation_ARRAY_Native
 * Method:    dot_
 * Signature: ([DI[DII)D
 */
JNIEXPORT jdouble JNICALL Java_jse_math_operation_ARRAY_00024Native_dot_1
  (JNIEnv *, jclass, jdoubleArray, jint, jdoubleArray, jint, jint);

/*
 * Class:     jse_math_operation_ARRAY_Native
 * Method:    dotOfThis_
 * Signature: ([DII)D
 */
JNIEXPORT jdouble JNICALL Java_jse_math_operation_ARRAY_00024Native_dotOfThis_1
  (JNIEnv *, jclass, jdoubleArray, jint, jint);

/*
 * Class:     jse_math_operation_ARRAY_Native
 * Method:    norm1OfThis_
 * Signature: ([DII)D
 */
JNIEXPORT jdouble JNICALL Java_jse_math_operation_ARRAY_00024Native_norm1OfThis_1
  (JNIEnv *, jclass, jdoubleArray, jint, jint);

/*
 * Class:     jse_math_operation_ARRAY_Native
 * Method:    matmulRC2Dest_
 * Signature: ([DI[DI[DIIII)V
 */
JNIEXPORT void JNICALL Java_jse_math_operation_ARRAY_00024Native_matmulRC2Dest_1
  (JNIEnv *, jclass, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
