/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_cptr_NestedIntCPointer */

#ifndef _Included_jse_cptr_NestedIntCPointer
#define _Included_jse_cptr_NestedIntCPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_cptr_NestedIntCPointer
 * Method:    fill0
 * Signature: (J[IIII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_NestedIntCPointer_fill0
  (JNIEnv *, jclass, jlong, jintArray, jint, jint, jint);

/*
 * Class:     jse_cptr_NestedIntCPointer
 * Method:    fill1
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_NestedIntCPointer_fill1
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     jse_cptr_NestedIntCPointer
 * Method:    parse2dest_
 * Signature: (J[IIII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_NestedIntCPointer_parse2dest_1
  (JNIEnv *, jclass, jlong, jintArray, jint, jint, jint);

/*
 * Class:     jse_cptr_NestedIntCPointer
 * Method:    getAt_
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_jse_cptr_NestedIntCPointer_getAt_1
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jse_cptr_NestedIntCPointer
 * Method:    putAt_
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_NestedIntCPointer_putAt_1
  (JNIEnv *, jclass, jlong, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
