/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_cptr_CPointer */

#ifndef _Included_jse_cptr_CPointer
#define _Included_jse_cptr_CPointer
#ifdef __cplusplus
extern "C" {
#endif
#undef jse_cptr_CPointer_TYPE_SIZE
#define jse_cptr_CPointer_TYPE_SIZE 1i64
/*
 * Class:     jse_cptr_CPointer
 * Method:    malloc_
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_CPointer_malloc_1
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_cptr_CPointer
 * Method:    calloc_
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_CPointer_calloc_1
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_cptr_CPointer
 * Method:    free_
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_CPointer_free_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_CPointer
 * Method:    memcpy_
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_CPointer_memcpy_1
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
