/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_cptr_IntCPointer */

#ifndef _Included_jse_cptr_IntCPointer
#define _Included_jse_cptr_IntCPointer
#ifdef __cplusplus
extern "C" {
#endif
#undef jse_cptr_IntCPointer_TYPE_SIZE
#define jse_cptr_IntCPointer_TYPE_SIZE 1i64
/*
 * Class:     jse_cptr_IntCPointer
 * Method:    typeSize_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_IntCPointer_typeSize_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_cptr_IntCPointer
 * Method:    fill0
 * Signature: (J[III)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_IntCPointer_fill0
  (JNIEnv *, jclass, jlong, jintArray, jint, jint);

/*
 * Class:     jse_cptr_IntCPointer
 * Method:    fill1
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_IntCPointer_fill1
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     jse_cptr_IntCPointer
 * Method:    parse2dest_
 * Signature: (J[III)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_IntCPointer_parse2dest_1
  (JNIEnv *, jclass, jlong, jintArray, jint, jint);

/*
 * Class:     jse_cptr_IntCPointer
 * Method:    get_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_cptr_IntCPointer_get_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_IntCPointer
 * Method:    getAt_
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_jse_cptr_IntCPointer_getAt_1
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_cptr_IntCPointer
 * Method:    set_
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_IntCPointer_set_1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_cptr_IntCPointer
 * Method:    putAt_
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_IntCPointer_putAt_1
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     jse_cptr_IntCPointer
 * Method:    next_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_IntCPointer_next_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_IntCPointer
 * Method:    rightShift_
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_IntCPointer_rightShift_1
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_cptr_IntCPointer
 * Method:    previous_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_IntCPointer_previous_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_IntCPointer
 * Method:    leftShift_
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_IntCPointer_leftShift_1
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
