/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_cptr_CPointer */

#ifndef _Included_jse_cptr_CPointer
#define _Included_jse_cptr_CPointer
#ifdef __cplusplus
extern "C" {
#endif
#undef jse_cptr_CPointer_TYPE_SIZE
#define jse_cptr_CPointer_TYPE_SIZE 1i64
/*
 * Class:     jse_cptr_CPointer
 * Method:    malloc1
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_CPointer_malloc1
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_cptr_CPointer
 * Method:    calloc1
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_CPointer_calloc1
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_cptr_CPointer
 * Method:    free0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_CPointer_free0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_CPointer
 * Method:    memcpy0
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_CPointer_memcpy0
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
