/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_cptr_NestedFloatCPointer */

#ifndef _Included_jse_cptr_NestedFloatCPointer
#define _Included_jse_cptr_NestedFloatCPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_cptr_NestedFloatCPointer
 * Method:    fill0
 * Signature: (J[FIII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_NestedFloatCPointer_fill0
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jint, jint);

/*
 * Class:     jse_cptr_NestedFloatCPointer
 * Method:    fillD0
 * Signature: (J[DIII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_NestedFloatCPointer_fillD0
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jint, jint);

/*
 * Class:     jse_cptr_NestedFloatCPointer
 * Method:    fill1
 * Signature: (JFII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_NestedFloatCPointer_fill1
  (JNIEnv *, jclass, jlong, jfloat, jint, jint);

/*
 * Class:     jse_cptr_NestedFloatCPointer
 * Method:    parse2dest_
 * Signature: (J[FIII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_NestedFloatCPointer_parse2dest_1
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jint, jint);

/*
 * Class:     jse_cptr_NestedFloatCPointer
 * Method:    parse2destD_
 * Signature: (J[DIII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_NestedFloatCPointer_parse2destD_1
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jint, jint);

/*
 * Class:     jse_cptr_NestedFloatCPointer
 * Method:    getAt_
 * Signature: (JII)F
 */
JNIEXPORT jfloat JNICALL Java_jse_cptr_NestedFloatCPointer_getAt_1
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jse_cptr_NestedFloatCPointer
 * Method:    putAt_
 * Signature: (JIIF)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_NestedFloatCPointer_putAt_1
  (JNIEnv *, jclass, jlong, jint, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
