/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_cptr_IntCPointer */

#ifndef _Included_jse_cptr_IntCPointer
#define _Included_jse_cptr_IntCPointer
#ifdef __cplusplus
extern "C" {
#endif
#undef jse_cptr_IntCPointer_TYPE_SIZE
#define jse_cptr_IntCPointer_TYPE_SIZE 1i64
/*
 * Class:     jse_cptr_IntCPointer
 * Method:    typeSize0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_IntCPointer_typeSize0
  (JNIEnv *, jclass);

/*
 * Class:     jse_cptr_IntCPointer
 * Method:    fill0
 * Signature: (J[III)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_IntCPointer_fill0
  (JNIEnv *, jclass, jlong, jintArray, jint, jint);

/*
 * Class:     jse_cptr_IntCPointer
 * Method:    fill2
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_IntCPointer_fill2
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     jse_cptr_IntCPointer
 * Method:    parse2dest0
 * Signature: (J[III)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_IntCPointer_parse2dest0
  (JNIEnv *, jclass, jlong, jintArray, jint, jint);

/*
 * Class:     jse_cptr_IntCPointer
 * Method:    get0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_cptr_IntCPointer_get0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_IntCPointer
 * Method:    getAt0
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_jse_cptr_IntCPointer_getAt0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_cptr_IntCPointer
 * Method:    set0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_IntCPointer_set0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_cptr_IntCPointer
 * Method:    putAt0
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_IntCPointer_putAt0
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     jse_cptr_IntCPointer
 * Method:    next0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_IntCPointer_next0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_IntCPointer
 * Method:    rightShift0
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_IntCPointer_rightShift0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_cptr_IntCPointer
 * Method:    previous0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_IntCPointer_previous0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_IntCPointer
 * Method:    leftShift0
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_IntCPointer_leftShift0
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
