/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_clib_CPointer */

#ifndef _Included_jse_clib_CPointer
#define _Included_jse_clib_CPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_clib_CPointer
 * Method:    malloc_
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_jse_clib_CPointer_malloc_1
  (JNIEnv *, jclass, jint);

/*
 * Class:     jse_clib_CPointer
 * Method:    calloc_
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_jse_clib_CPointer_calloc_1
  (JNIEnv *, jclass, jint);

/*
 * Class:     jse_clib_CPointer
 * Method:    free_
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jse_clib_CPointer_free_1
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
