/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_cptr_Int64CPointer */

#ifndef _Included_jse_cptr_Int64CPointer
#define _Included_jse_cptr_Int64CPointer
#ifdef __cplusplus
extern "C" {
#endif
#undef jse_cptr_Int64CPointer_TYPE_SIZE
#define jse_cptr_Int64CPointer_TYPE_SIZE 1i64
/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    typeSize_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_Int64CPointer_typeSize_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    fill0
 * Signature: (J[JII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_Int64CPointer_fill0
  (JNIEnv *, jclass, jlong, jlongArray, jint, jint);

/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    fill1
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_Int64CPointer_fill1
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    parse2dest_
 * Signature: (J[JII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_Int64CPointer_parse2dest_1
  (JNIEnv *, jclass, jlong, jlongArray, jint, jint);

/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    get_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_Int64CPointer_get_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    getAt_
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_Int64CPointer_getAt_1
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    set_
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_Int64CPointer_set_1
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    putAt_
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_Int64CPointer_putAt_1
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    next_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_Int64CPointer_next_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    rightShift_
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_Int64CPointer_rightShift_1
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    previous_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_Int64CPointer_previous_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    leftShift_
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_Int64CPointer_leftShift_1
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
