/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_cptr_Int64CPointer */

#ifndef _Included_jse_cptr_Int64CPointer
#define _Included_jse_cptr_Int64CPointer
#ifdef __cplusplus
extern "C" {
#endif
#undef jse_cptr_Int64CPointer_TYPE_SIZE
#define jse_cptr_Int64CPointer_TYPE_SIZE 1i64
/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    typeSize0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_Int64CPointer_typeSize0
  (JNIEnv *, jclass);

/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    fill0
 * Signature: (J[JII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_Int64CPointer_fill0
  (JNIEnv *, jclass, jlong, jlongArray, jint, jint);

/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    fill2
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_Int64CPointer_fill2
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    parse2dest0
 * Signature: (J[JII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_Int64CPointer_parse2dest0
  (JNIEnv *, jclass, jlong, jlongArray, jint, jint);

/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    get0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_Int64CPointer_get0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    getAt0
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_Int64CPointer_getAt0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    set0
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_Int64CPointer_set0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    putAt0
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_Int64CPointer_putAt0
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    next0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_Int64CPointer_next0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    rightShift0
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_Int64CPointer_rightShift0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    previous0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_Int64CPointer_previous0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_Int64CPointer
 * Method:    leftShift0
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_Int64CPointer_leftShift0
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
