/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_clib_DoubleCPointer */

#ifndef _Included_jse_clib_DoubleCPointer
#define _Included_jse_clib_DoubleCPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_clib_DoubleCPointer
 * Method:    typeSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_clib_DoubleCPointer_typeSize
  (JNIEnv *, jclass);

/*
 * Class:     jse_clib_DoubleCPointer
 * Method:    fill_
 * Signature: (J[DII)V
 */
JNIEXPORT void JNICALL Java_jse_clib_DoubleCPointer_fill_1
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jint);

/*
 * Class:     jse_clib_DoubleCPointer
 * Method:    parse2dest_
 * Signature: (J[DII)V
 */
JNIEXPORT void JNICALL Java_jse_clib_DoubleCPointer_parse2dest_1
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jint);

/*
 * Class:     jse_clib_DoubleCPointer
 * Method:    get_
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_clib_DoubleCPointer_get_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_clib_DoubleCPointer
 * Method:    getAt_
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_jse_clib_DoubleCPointer_getAt_1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_clib_DoubleCPointer
 * Method:    set_
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_jse_clib_DoubleCPointer_set_1
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     jse_clib_DoubleCPointer
 * Method:    putAt_
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_jse_clib_DoubleCPointer_putAt_1
  (JNIEnv *, jclass, jlong, jint, jdouble);

/*
 * Class:     jse_clib_DoubleCPointer
 * Method:    next_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_clib_DoubleCPointer_next_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_clib_DoubleCPointer
 * Method:    rightShift_
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_jse_clib_DoubleCPointer_rightShift_1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_clib_DoubleCPointer
 * Method:    previous_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_clib_DoubleCPointer_previous_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_clib_DoubleCPointer
 * Method:    leftShift_
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_jse_clib_DoubleCPointer_leftShift_1
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
