/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_cptr_AnyCPointer */

#ifndef _Included_jse_cptr_AnyCPointer
#define _Included_jse_cptr_AnyCPointer
#ifdef __cplusplus
extern "C" {
#endif
#undef jse_cptr_AnyCPointer_TYPE_SIZE
#define jse_cptr_AnyCPointer_TYPE_SIZE 1i64
/*
 * Class:     jse_cptr_AnyCPointer
 * Method:    typeSize0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_AnyCPointer_typeSize0
  (JNIEnv *, jclass);

/*
 * Class:     jse_cptr_AnyCPointer
 * Method:    get0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_AnyCPointer_get0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_AnyCPointer
 * Method:    getAt0
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_AnyCPointer_getAt0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_cptr_AnyCPointer
 * Method:    set0
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_AnyCPointer_set0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_cptr_AnyCPointer
 * Method:    putAt0
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_AnyCPointer_putAt0
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jse_cptr_AnyCPointer
 * Method:    next0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_AnyCPointer_next0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_AnyCPointer
 * Method:    rightShift0
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_AnyCPointer_rightShift0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_cptr_AnyCPointer
 * Method:    previous0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_AnyCPointer_previous0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_AnyCPointer
 * Method:    leftShift0
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_AnyCPointer_leftShift0
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
