/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_clib_NestedDoubleCPointer */

#ifndef _Included_jse_clib_NestedDoubleCPointer
#define _Included_jse_clib_NestedDoubleCPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_clib_NestedDoubleCPointer
 * Method:    fill_
 * Signature: (J[DIII)V
 */
JNIEXPORT void JNICALL Java_jse_clib_NestedDoubleCPointer_fill_1
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jint, jint);

/*
 * Class:     jse_clib_NestedDoubleCPointer
 * Method:    parse2dest_
 * Signature: (J[DIII)V
 */
JNIEXPORT void JNICALL Java_jse_clib_NestedDoubleCPointer_parse2dest_1
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jint, jint);

/*
 * Class:     jse_clib_NestedDoubleCPointer
 * Method:    getAt_
 * Signature: (JII)D
 */
JNIEXPORT jdouble JNICALL Java_jse_clib_NestedDoubleCPointer_getAt_1
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jse_clib_NestedDoubleCPointer
 * Method:    putAt_
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_jse_clib_NestedDoubleCPointer_putAt_1
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
