/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_cptr_AnyCPointer */

#ifndef _Included_jse_cptr_AnyCPointer
#define _Included_jse_cptr_AnyCPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_cptr_AnyCPointer
 * Method:    typeSize_
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_cptr_AnyCPointer_typeSize_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_cptr_AnyCPointer
 * Method:    get_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_AnyCPointer_get_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_AnyCPointer
 * Method:    getAt_
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_AnyCPointer_getAt_1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_cptr_AnyCPointer
 * Method:    set_
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_AnyCPointer_set_1
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_cptr_AnyCPointer
 * Method:    putAt_
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_AnyCPointer_putAt_1
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     jse_cptr_AnyCPointer
 * Method:    next_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_AnyCPointer_next_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_AnyCPointer
 * Method:    rightShift_
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_AnyCPointer_rightShift_1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_cptr_AnyCPointer
 * Method:    previous_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_AnyCPointer_previous_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_AnyCPointer
 * Method:    leftShift_
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_AnyCPointer_leftShift_1
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
