/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_cptr_NestedDoubleCPointer */

#ifndef _Included_jse_cptr_NestedDoubleCPointer
#define _Included_jse_cptr_NestedDoubleCPointer
#ifdef __cplusplus
extern "C" {
#endif
#undef jse_cptr_NestedDoubleCPointer_TYPE_SIZE
#define jse_cptr_NestedDoubleCPointer_TYPE_SIZE 1i64
/*
 * Class:     jse_cptr_NestedDoubleCPointer
 * Method:    fill0
 * Signature: (J[DIII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_NestedDoubleCPointer_fill0
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jint, jint);

/*
 * Class:     jse_cptr_NestedDoubleCPointer
 * Method:    fill1
 * Signature: (JDJJ)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_NestedDoubleCPointer_fill1
  (JNIEnv *, jclass, jlong, jdouble, jlong, jlong);

/*
 * Class:     jse_cptr_NestedDoubleCPointer
 * Method:    parse2dest_
 * Signature: (J[DIII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_NestedDoubleCPointer_parse2dest_1
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jint, jint);

/*
 * Class:     jse_cptr_NestedDoubleCPointer
 * Method:    getAt_
 * Signature: (JJJ)D
 */
JNIEXPORT jdouble JNICALL Java_jse_cptr_NestedDoubleCPointer_getAt_1
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jse_cptr_NestedDoubleCPointer
 * Method:    putAt_
 * Signature: (JJJD)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_NestedDoubleCPointer_putAt_1
  (JNIEnv *, jclass, jlong, jlong, jlong, jdouble);

#ifdef __cplusplus
}
#endif
#endif
