/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_clib_IntCPointer */

#ifndef _Included_jse_clib_IntCPointer
#define _Included_jse_clib_IntCPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_clib_IntCPointer
 * Method:    typeSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_clib_IntCPointer_typeSize
  (JNIEnv *, jclass);

/*
 * Class:     jse_clib_IntCPointer
 * Method:    fill0
 * Signature: (J[III)V
 */
JNIEXPORT void JNICALL Java_jse_clib_IntCPointer_fill0
  (JNIEnv *, jclass, jlong, jintArray, jint, jint);

/*
 * Class:     jse_clib_IntCPointer
 * Method:    fill1
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_jse_clib_IntCPointer_fill1
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jse_clib_IntCPointer
 * Method:    parse2dest_
 * Signature: (J[III)V
 */
JNIEXPORT void JNICALL Java_jse_clib_IntCPointer_parse2dest_1
  (JNIEnv *, jclass, jlong, jintArray, jint, jint);

/*
 * Class:     jse_clib_IntCPointer
 * Method:    get_
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jse_clib_IntCPointer_get_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_clib_IntCPointer
 * Method:    getAt_
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_jse_clib_IntCPointer_getAt_1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_clib_IntCPointer
 * Method:    set_
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_jse_clib_IntCPointer_set_1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_clib_IntCPointer
 * Method:    putAt_
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_jse_clib_IntCPointer_putAt_1
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     jse_clib_IntCPointer
 * Method:    next_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_clib_IntCPointer_next_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_clib_IntCPointer
 * Method:    rightShift_
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_jse_clib_IntCPointer_rightShift_1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_clib_IntCPointer
 * Method:    previous_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_clib_IntCPointer_previous_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_clib_IntCPointer
 * Method:    leftShift_
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_jse_clib_IntCPointer_leftShift_1
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
