/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_cptr_FloatCPointer */

#ifndef _Included_jse_cptr_FloatCPointer
#define _Included_jse_cptr_FloatCPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jse_cptr_FloatCPointer
 * Method:    typeSize_
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jse_cptr_FloatCPointer_typeSize_1
  (JNIEnv *, jclass);

/*
 * Class:     jse_cptr_FloatCPointer
 * Method:    fill0
 * Signature: (J[FII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_FloatCPointer_fill0
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jint);

/*
 * Class:     jse_cptr_FloatCPointer
 * Method:    fillD0
 * Signature: (J[DII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_FloatCPointer_fillD0
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jint);

/*
 * Class:     jse_cptr_FloatCPointer
 * Method:    fill1
 * Signature: (JFI)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_FloatCPointer_fill1
  (JNIEnv *, jclass, jlong, jfloat, jint);

/*
 * Class:     jse_cptr_FloatCPointer
 * Method:    parse2dest_
 * Signature: (J[FII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_FloatCPointer_parse2dest_1
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jint);

/*
 * Class:     jse_cptr_FloatCPointer
 * Method:    parse2destD_
 * Signature: (J[DII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_FloatCPointer_parse2destD_1
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jint);

/*
 * Class:     jse_cptr_FloatCPointer
 * Method:    get_
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_jse_cptr_FloatCPointer_get_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_FloatCPointer
 * Method:    getAt_
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_jse_cptr_FloatCPointer_getAt_1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_cptr_FloatCPointer
 * Method:    set_
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_FloatCPointer_set_1
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     jse_cptr_FloatCPointer
 * Method:    putAt_
 * Signature: (JIF)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_FloatCPointer_putAt_1
  (JNIEnv *, jclass, jlong, jint, jfloat);

/*
 * Class:     jse_cptr_FloatCPointer
 * Method:    next_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_FloatCPointer_next_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_FloatCPointer
 * Method:    rightShift_
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_FloatCPointer_rightShift_1
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jse_cptr_FloatCPointer
 * Method:    previous_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_FloatCPointer_previous_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_FloatCPointer
 * Method:    leftShift_
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_FloatCPointer_leftShift_1
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
