/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_cptr_DoubleCPointer */

#ifndef _Included_jse_cptr_DoubleCPointer
#define _Included_jse_cptr_DoubleCPointer
#ifdef __cplusplus
extern "C" {
#endif
#undef jse_cptr_DoubleCPointer_TYPE_SIZE
#define jse_cptr_DoubleCPointer_TYPE_SIZE 1i64
/*
 * Class:     jse_cptr_DoubleCPointer
 * Method:    typeSize0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_DoubleCPointer_typeSize0
  (JNIEnv *, jclass);

/*
 * Class:     jse_cptr_DoubleCPointer
 * Method:    fill0
 * Signature: (J[DII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_DoubleCPointer_fill0
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jint);

/*
 * Class:     jse_cptr_DoubleCPointer
 * Method:    fillF0
 * Signature: (J[FII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_DoubleCPointer_fillF0
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jint);

/*
 * Class:     jse_cptr_DoubleCPointer
 * Method:    fillF1
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_DoubleCPointer_fillF1
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jse_cptr_DoubleCPointer
 * Method:    fill2
 * Signature: (JDJ)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_DoubleCPointer_fill2
  (JNIEnv *, jclass, jlong, jdouble, jlong);

/*
 * Class:     jse_cptr_DoubleCPointer
 * Method:    parse2dest0
 * Signature: (J[DII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_DoubleCPointer_parse2dest0
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jint);

/*
 * Class:     jse_cptr_DoubleCPointer
 * Method:    parse2destF0
 * Signature: (J[FII)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_DoubleCPointer_parse2destF0
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jint);

/*
 * Class:     jse_cptr_DoubleCPointer
 * Method:    parse2destF1
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_DoubleCPointer_parse2destF1
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jse_cptr_DoubleCPointer
 * Method:    get0
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jse_cptr_DoubleCPointer_get0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_DoubleCPointer
 * Method:    getAt0
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_jse_cptr_DoubleCPointer_getAt0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_cptr_DoubleCPointer
 * Method:    set0
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_DoubleCPointer_set0
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     jse_cptr_DoubleCPointer
 * Method:    putAt0
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_jse_cptr_DoubleCPointer_putAt0
  (JNIEnv *, jclass, jlong, jlong, jdouble);

/*
 * Class:     jse_cptr_DoubleCPointer
 * Method:    next0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_DoubleCPointer_next0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_DoubleCPointer
 * Method:    rightShift0
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_DoubleCPointer_rightShift0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jse_cptr_DoubleCPointer
 * Method:    previous0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_DoubleCPointer_previous0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jse_cptr_DoubleCPointer
 * Method:    leftShift0
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jse_cptr_DoubleCPointer_leftShift0
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
