/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsex_nnap_basis_MultiLayerSphericalChebyshev */

#ifndef _Included_jsex_nnap_basis_MultiLayerSphericalChebyshev
#define _Included_jsex_nnap_basis_MultiLayerSphericalChebyshev
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsex_nnap_basis_MultiLayerSphericalChebyshev
 * Method:    forwardEmb0
 * Signature: ([D[DI[D[D[II)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_MultiLayerSphericalChebyshev_forwardEmb0
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jdoubleArray, jdoubleArray, jintArray, jint);

/*
 * Class:     jsex_nnap_basis_MultiLayerSphericalChebyshev
 * Method:    forward1
 * Signature: ([D[D[D[II[DI[DIZIDIIII[D[D[II[DID[D[D)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_MultiLayerSphericalChebyshev_forward1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jint, jdoubleArray, jint, jboolean, jint, jdouble, jint, jint, jint, jint, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jint, jdouble, jdoubleArray, jdoubleArray);

/*
 * Class:     jsex_nnap_basis_MultiLayerSphericalChebyshev
 * Method:    backward1
 * Signature: ([D[D[D[II[DI[DI[DI[DIIDIIII[D[II[DID[D)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_MultiLayerSphericalChebyshev_backward1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jint, jdouble, jint, jint, jint, jint, jdoubleArray, jintArray, jint, jdoubleArray, jint, jdouble, jdoubleArray);

/*
 * Class:     jsex_nnap_basis_MultiLayerSphericalChebyshev
 * Method:    forwardForce1
 * Signature: ([D[D[D[II[DI[D[D[D[DI[DIZIDIIII[D[II[DID[D[D)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_MultiLayerSphericalChebyshev_forwardForce1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdoubleArray, jint, jboolean, jint, jdouble, jint, jint, jint, jint, jdoubleArray, jintArray, jint, jdoubleArray, jint, jdouble, jdoubleArray, jdoubleArray);

/*
 * Class:     jsex_nnap_basis_MultiLayerSphericalChebyshev
 * Method:    backwardForce1
 * Signature: ([D[D[D[II[DI[D[D[D[DI[DI[DI[DI[DI[DIZIDIIII[D[II[DID[D)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_MultiLayerSphericalChebyshev_backwardForce1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jboolean, jint, jdouble, jint, jint, jint, jint, jdoubleArray, jintArray, jint, jdoubleArray, jint, jdouble, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
