/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsex_nnap_nn_FeedForward */

#ifndef _Included_jsex_nnap_nn_FeedForward
#define _Included_jsex_nnap_nn_FeedForward
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsex_nnap_nn_FeedForward
 * Method:    forward1
 * Signature: ([DII[II[D[D[DD[D)D
 */
JNIEXPORT jdouble JNICALL Java_jsex_nnap_nn_FeedForward_forward1
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jintArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdouble, jdoubleArray);

/*
 * Class:     jsex_nnap_nn_FeedForward
 * Method:    backward1
 * Signature: ([DI[DII[II[D[D[DD[D[D)D
 */
JNIEXPORT jdouble JNICALL Java_jsex_nnap_nn_FeedForward_backward1
  (JNIEnv *, jclass, jdoubleArray, jint, jdoubleArray, jint, jint, jintArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdouble, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
