/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsex_nnap_basis_EquivariantSphericalChebyshev */

#ifndef _Included_jsex_nnap_basis_EquivariantSphericalChebyshev
#define _Included_jsex_nnap_basis_EquivariantSphericalChebyshev
#ifdef __cplusplus
extern "C" {
#endif
#undef jsex_nnap_basis_EquivariantSphericalChebyshev_WTYPE_DEFAULT
#define jsex_nnap_basis_EquivariantSphericalChebyshev_WTYPE_DEFAULT 0L
#undef jsex_nnap_basis_EquivariantSphericalChebyshev_WTYPE_NONE
#define jsex_nnap_basis_EquivariantSphericalChebyshev_WTYPE_NONE -1L
#undef jsex_nnap_basis_EquivariantSphericalChebyshev_WTYPE_FULL
#define jsex_nnap_basis_EquivariantSphericalChebyshev_WTYPE_FULL 2L
#undef jsex_nnap_basis_EquivariantSphericalChebyshev_WTYPE_EXFULL
#define jsex_nnap_basis_EquivariantSphericalChebyshev_WTYPE_EXFULL 3L
#undef jsex_nnap_basis_EquivariantSphericalChebyshev_WTYPE_FUSE
#define jsex_nnap_basis_EquivariantSphericalChebyshev_WTYPE_FUSE 4L
#undef jsex_nnap_basis_EquivariantSphericalChebyshev_WTYPE_EXFUSE
#define jsex_nnap_basis_EquivariantSphericalChebyshev_WTYPE_EXFUSE 6L
#undef jsex_nnap_basis_EquivariantSphericalChebyshev_FUSE_STYLE_LIMITED
#define jsex_nnap_basis_EquivariantSphericalChebyshev_FUSE_STYLE_LIMITED 0L
#undef jsex_nnap_basis_EquivariantSphericalChebyshev_FUSE_STYLE_EXTENSIVE
#define jsex_nnap_basis_EquivariantSphericalChebyshev_FUSE_STYLE_EXTENSIVE 1L
#undef jsex_nnap_basis_EquivariantSphericalChebyshev_DEFAULT_NMAX
#define jsex_nnap_basis_EquivariantSphericalChebyshev_DEFAULT_NMAX 5L
#undef jsex_nnap_basis_EquivariantSphericalChebyshev_DEFAULT_LMAX
#define jsex_nnap_basis_EquivariantSphericalChebyshev_DEFAULT_LMAX 6L
#undef jsex_nnap_basis_EquivariantSphericalChebyshev_DEFAULT_L3MAX
#define jsex_nnap_basis_EquivariantSphericalChebyshev_DEFAULT_L3MAX 0L
#undef jsex_nnap_basis_EquivariantSphericalChebyshev_DEFAULT_L4MAX
#define jsex_nnap_basis_EquivariantSphericalChebyshev_DEFAULT_L4MAX 0L
#undef jsex_nnap_basis_EquivariantSphericalChebyshev_DEFAULT_NORADIAL
#define jsex_nnap_basis_EquivariantSphericalChebyshev_DEFAULT_NORADIAL 0L
#undef jsex_nnap_basis_EquivariantSphericalChebyshev_DEFAULT_RCUT
#define jsex_nnap_basis_EquivariantSphericalChebyshev_DEFAULT_RCUT 6.0
#undef jsex_nnap_basis_EquivariantSphericalChebyshev_DEFAULT_LMAX
#define jsex_nnap_basis_EquivariantSphericalChebyshev_DEFAULT_LMAX 4L
/*
 * Class:     jsex_nnap_basis_EquivariantSphericalChebyshev
 * Method:    forward1
 * Signature: ([D[D[D[II[DI[DIZIDIIIIII[DI[D[I[DI[D[D)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_EquivariantSphericalChebyshev_forward1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jint, jdoubleArray, jint, jboolean, jint, jdouble, jint, jint, jint, jint, jint, jint, jdoubleArray, jint, jdoubleArray, jintArray, jdoubleArray, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     jsex_nnap_basis_EquivariantSphericalChebyshev
 * Method:    backward1
 * Signature: ([D[D[D[II[DI[DI[DI[DIIDIIIIIII[D[I[DI[D)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_EquivariantSphericalChebyshev_backward1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jint, jdouble, jint, jint, jint, jint, jint, jint, jint, jdoubleArray, jintArray, jdoubleArray, jint, jdoubleArray);

/*
 * Class:     jsex_nnap_basis_EquivariantSphericalChebyshev
 * Method:    forwardForce1
 * Signature: ([D[D[D[II[DI[D[D[D[DI[DIZIDIIIIII[DI[D[I[DI[D[D)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_EquivariantSphericalChebyshev_forwardForce1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdoubleArray, jint, jboolean, jint, jdouble, jint, jint, jint, jint, jint, jint, jdoubleArray, jint, jdoubleArray, jintArray, jdoubleArray, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     jsex_nnap_basis_EquivariantSphericalChebyshev
 * Method:    backwardForce1
 * Signature: ([D[D[D[II[DI[D[D[D[DI[DI[DI[DI[DI[DIZIDIIIIII[DI[D[I[DI[D)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_EquivariantSphericalChebyshev_backwardForce1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jboolean, jint, jdouble, jint, jint, jint, jint, jint, jint, jdoubleArray, jint, jdoubleArray, jintArray, jdoubleArray, jint, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
