/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsex_nnap_basis_Chebyshev */

#ifndef _Included_jsex_nnap_basis_Chebyshev
#define _Included_jsex_nnap_basis_Chebyshev
#ifdef __cplusplus
extern "C" {
#endif
#undef jsex_nnap_basis_Chebyshev_WTYPE_DEFAULT
#define jsex_nnap_basis_Chebyshev_WTYPE_DEFAULT 0L
#undef jsex_nnap_basis_Chebyshev_WTYPE_NONE
#define jsex_nnap_basis_Chebyshev_WTYPE_NONE -1L
#undef jsex_nnap_basis_Chebyshev_WTYPE_SINGLE
#define jsex_nnap_basis_Chebyshev_WTYPE_SINGLE 1L
#undef jsex_nnap_basis_Chebyshev_WTYPE_FULL
#define jsex_nnap_basis_Chebyshev_WTYPE_FULL 2L
#undef jsex_nnap_basis_Chebyshev_WTYPE_EXFULL
#define jsex_nnap_basis_Chebyshev_WTYPE_EXFULL 3L
#undef jsex_nnap_basis_Chebyshev_DEFAULT_NMAX
#define jsex_nnap_basis_Chebyshev_DEFAULT_NMAX 5L
#undef jsex_nnap_basis_Chebyshev_DEFAULT_RCUT
#define jsex_nnap_basis_Chebyshev_DEFAULT_RCUT 6.0
/*
 * Class:     jsex_nnap_basis_Chebyshev
 * Method:    eval1
 * Signature: ([D[D[D[II[D[DI[IIZIDII)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_Chebyshev_eval1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jdoubleArray, jint, jintArray, jint, jboolean, jint, jdouble, jint, jint);

/*
 * Class:     jsex_nnap_basis_Chebyshev
 * Method:    evalGrad1
 * Signature: ([D[D[D[II[D[D[D[D[D[II[II[DI[DI[DIIDII)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_Chebyshev_evalGrad1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jintArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jint, jdouble, jint, jint);

/*
 * Class:     jsex_nnap_basis_Chebyshev
 * Method:    evalGradAndForceDot1
 * Signature: ([D[D[D[II[D[D[D[D[D[DI[D[D[DIDII)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_Chebyshev_evalGradAndForceDot1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jint);

/*
 * Class:     jsex_nnap_basis_Chebyshev
 * Method:    evalGradWithShift1
 * Signature: ([D[D[D[II[D[D[D[D[DII[D[D[DIDII)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_Chebyshev_evalGradWithShift1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
