/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsex_nnap_basis_SphericalChebyshev */

#ifndef _Included_jsex_nnap_basis_SphericalChebyshev
#define _Included_jsex_nnap_basis_SphericalChebyshev
#ifdef __cplusplus
extern "C" {
#endif
#undef jsex_nnap_basis_SphericalChebyshev_WTYPE_DEFAULT
#define jsex_nnap_basis_SphericalChebyshev_WTYPE_DEFAULT 0L
#undef jsex_nnap_basis_SphericalChebyshev_WTYPE_NONE
#define jsex_nnap_basis_SphericalChebyshev_WTYPE_NONE -1L
#undef jsex_nnap_basis_SphericalChebyshev_WTYPE_FULL
#define jsex_nnap_basis_SphericalChebyshev_WTYPE_FULL 2L
#undef jsex_nnap_basis_SphericalChebyshev_WTYPE_EXFULL
#define jsex_nnap_basis_SphericalChebyshev_WTYPE_EXFULL 3L
#undef jsex_nnap_basis_SphericalChebyshev_WTYPE_FUSE
#define jsex_nnap_basis_SphericalChebyshev_WTYPE_FUSE 4L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_FUSE_SIZE
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_FUSE_SIZE 1L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_NMAX
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_NMAX 5L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_LMAX
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_LMAX 6L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_L3MAX
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_L3MAX 0L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_NORADIAL
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_NORADIAL 0L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_L3CROSS
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_L3CROSS 1L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_RCUT
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_RCUT 6.0
/*
 * Class:     jsex_nnap_basis_SphericalChebyshev
 * Method:    eval1
 * Signature: ([D[D[D[II[D[D[D[DI[IIZIDIIZIZI[DI)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_SphericalChebyshev_eval1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jintArray, jint, jboolean, jint, jdouble, jint, jint, jboolean, jint, jboolean, jint, jdoubleArray, jint);

/*
 * Class:     jsex_nnap_basis_SphericalChebyshev
 * Method:    backward1
 * Signature: ([D[D[D[II[D[D[D[D[D[DI[DIIDIIZIZI[DI)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_SphericalChebyshev_backward1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdoubleArray, jint, jint, jdouble, jint, jint, jboolean, jint, jboolean, jint, jdoubleArray, jint);

/*
 * Class:     jsex_nnap_basis_SphericalChebyshev
 * Method:    evalGrad1
 * Signature: ([D[D[D[II[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[II[II[DI[DI[DIIDIIZIZI[DI)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_SphericalChebyshev_evalGrad1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jintArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jint, jdouble, jint, jint, jboolean, jint, jboolean, jint, jdoubleArray, jint);

/*
 * Class:     jsex_nnap_basis_SphericalChebyshev
 * Method:    evalForce1
 * Signature: ([D[D[D[II[D[D[D[D[D[D[D[D[D[D[D[D[D[D[DI[D[D[DIDIIZIZI[DI)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_SphericalChebyshev_evalForce1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jint, jboolean, jint, jboolean, jint, jdoubleArray, jint);

/*
 * Class:     jsex_nnap_basis_SphericalChebyshev
 * Method:    evalGradWithShift1
 * Signature: ([D[D[D[II[D[D[D[D[D[D[D[D[D[D[D[D[D[D[DII[D[D[DIDIIZIZI[DI)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_SphericalChebyshev_evalGradWithShift1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jint, jboolean, jint, jboolean, jint, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
