/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsex_nnap_basis_SphericalChebyshev */

#ifndef _Included_jsex_nnap_basis_SphericalChebyshev
#define _Included_jsex_nnap_basis_SphericalChebyshev
#ifdef __cplusplus
extern "C" {
#endif
#undef jsex_nnap_basis_SphericalChebyshev_WTYPE_DEFAULT
#define jsex_nnap_basis_SphericalChebyshev_WTYPE_DEFAULT 0L
#undef jsex_nnap_basis_SphericalChebyshev_WTYPE_NONE
#define jsex_nnap_basis_SphericalChebyshev_WTYPE_NONE -1L
#undef jsex_nnap_basis_SphericalChebyshev_WTYPE_SINGLE
#define jsex_nnap_basis_SphericalChebyshev_WTYPE_SINGLE 1L
#undef jsex_nnap_basis_SphericalChebyshev_WTYPE_FULL
#define jsex_nnap_basis_SphericalChebyshev_WTYPE_FULL 2L
#undef jsex_nnap_basis_SphericalChebyshev_WTYPE_EXFULL
#define jsex_nnap_basis_SphericalChebyshev_WTYPE_EXFULL 3L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_NMAX
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_NMAX 5L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_LMAX
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_LMAX 6L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_L3MAX
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_L3MAX 0L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_NORADIAL
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_NORADIAL 0L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_L3CROSS
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_L3CROSS 1L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_RCUT
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_RCUT 6.0
/*
 * Class:     jsex_nnap_basis_SphericalChebyshev
 * Method:    eval1
 * Signature: ([D[D[D[II[D[D[D[DIZIDIIZIZI)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_SphericalChebyshev_eval1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jboolean, jint, jdouble, jint, jint, jboolean, jint, jboolean, jint);

/*
 * Class:     jsex_nnap_basis_SphericalChebyshev
 * Method:    evalPartial1
 * Signature: ([D[D[D[II[D[D[D[D[D[D[D[D[D[D[D[D[D[D[DII[D[D[DIDIIZIZI)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_SphericalChebyshev_evalPartial1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jint, jboolean, jint, jboolean, jint);

/*
 * Class:     jsex_nnap_basis_SphericalChebyshev
 * Method:    evalPartialAndForceDot1
 * Signature: ([D[D[D[II[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[DI[D[D[DIDIIZIZI)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_SphericalChebyshev_evalPartialAndForceDot1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jint, jboolean, jint, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
