/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsex_nnap_basis_Chebyshev */

#ifndef _Included_jsex_nnap_basis_Chebyshev
#define _Included_jsex_nnap_basis_Chebyshev
#ifdef __cplusplus
extern "C" {
#endif
#undef jsex_nnap_basis_Chebyshev_WTYPE_DEFAULT
#define jsex_nnap_basis_Chebyshev_WTYPE_DEFAULT 0L
#undef jsex_nnap_basis_Chebyshev_WTYPE_NONE
#define jsex_nnap_basis_Chebyshev_WTYPE_NONE -1L
#undef jsex_nnap_basis_Chebyshev_WTYPE_FULL
#define jsex_nnap_basis_Chebyshev_WTYPE_FULL 2L
#undef jsex_nnap_basis_Chebyshev_WTYPE_EXFULL
#define jsex_nnap_basis_Chebyshev_WTYPE_EXFULL 3L
#undef jsex_nnap_basis_Chebyshev_WTYPE_FUSE
#define jsex_nnap_basis_Chebyshev_WTYPE_FUSE 4L
#undef jsex_nnap_basis_Chebyshev_DEFAULT_FUSE_SIZE
#define jsex_nnap_basis_Chebyshev_DEFAULT_FUSE_SIZE 1L
#undef jsex_nnap_basis_Chebyshev_DEFAULT_NMAX
#define jsex_nnap_basis_Chebyshev_DEFAULT_NMAX 5L
#undef jsex_nnap_basis_Chebyshev_DEFAULT_RCUT
#define jsex_nnap_basis_Chebyshev_DEFAULT_RCUT 6.0
/*
 * Class:     jsex_nnap_basis_Chebyshev
 * Method:    eval1
 * Signature: ([D[D[D[II[D[DI[IIZIDII[DI)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_Chebyshev_eval1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jdoubleArray, jint, jintArray, jint, jboolean, jint, jdouble, jint, jint, jdoubleArray, jint);

/*
 * Class:     jsex_nnap_basis_Chebyshev
 * Method:    backward1
 * Signature: ([D[D[D[II[D[DI[DIIDIII)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_Chebyshev_backward1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jdoubleArray, jint, jdoubleArray, jint, jint, jdouble, jint, jint, jint);

/*
 * Class:     jsex_nnap_basis_Chebyshev
 * Method:    evalGrad1
 * Signature: ([D[D[D[II[D[D[D[D[D[II[II[DI[DI[DIIDII[DI)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_Chebyshev_evalGrad1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jintArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jint, jdouble, jint, jint, jdoubleArray, jint);

/*
 * Class:     jsex_nnap_basis_Chebyshev
 * Method:    evalForce1
 * Signature: ([D[D[D[II[D[D[D[D[D[DI[D[D[DIDII[DI)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_Chebyshev_evalForce1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jint, jdoubleArray, jint);

/*
 * Class:     jsex_nnap_basis_Chebyshev
 * Method:    evalGradWithShift1
 * Signature: ([D[D[D[II[D[D[D[D[DII[D[D[DIDII[DI)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_Chebyshev_evalGradWithShift1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jint, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
