/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsex_nnap_basis_SphericalChebyshev */

#ifndef _Included_jsex_nnap_basis_SphericalChebyshev
#define _Included_jsex_nnap_basis_SphericalChebyshev
#ifdef __cplusplus
extern "C" {
#endif
#undef jsex_nnap_basis_SphericalChebyshev_WTYPE_DEFAULT
#define jsex_nnap_basis_SphericalChebyshev_WTYPE_DEFAULT 0L
#undef jsex_nnap_basis_SphericalChebyshev_WTYPE_NONE
#define jsex_nnap_basis_SphericalChebyshev_WTYPE_NONE -1L
#undef jsex_nnap_basis_SphericalChebyshev_WTYPE_FULL
#define jsex_nnap_basis_SphericalChebyshev_WTYPE_FULL 2L
#undef jsex_nnap_basis_SphericalChebyshev_WTYPE_EXFULL
#define jsex_nnap_basis_SphericalChebyshev_WTYPE_EXFULL 3L
#undef jsex_nnap_basis_SphericalChebyshev_WTYPE_FUSE
#define jsex_nnap_basis_SphericalChebyshev_WTYPE_FUSE 4L
#undef jsex_nnap_basis_SphericalChebyshev_WTYPE_RFUSE
#define jsex_nnap_basis_SphericalChebyshev_WTYPE_RFUSE 5L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_FUSE_SIZE
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_FUSE_SIZE 1L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_NMAX
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_NMAX 5L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_LMAX
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_LMAX 6L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_L3MAX
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_L3MAX 0L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_L4MAX
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_L4MAX 0L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_NORADIAL
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_NORADIAL 0L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_L3CROSS
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_L3CROSS 1L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_L4CROSS
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_L4CROSS 1L
#undef jsex_nnap_basis_SphericalChebyshev_DEFAULT_RCUT
#define jsex_nnap_basis_SphericalChebyshev_DEFAULT_RCUT 6.0
/*
 * Class:     jsex_nnap_basis_SphericalChebyshev
 * Method:    forward1
 * Signature: ([D[D[D[II[DI[DIZIDIIZIZIZI[DI[DI)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_SphericalChebyshev_forward1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jint, jdoubleArray, jint, jboolean, jint, jdouble, jint, jint, jboolean, jint, jboolean, jint, jboolean, jint, jdoubleArray, jint, jdoubleArray, jint);

/*
 * Class:     jsex_nnap_basis_SphericalChebyshev
 * Method:    backward1
 * Signature: ([D[D[D[II[DI[DI[DI[DIIDIIZIZIZII[DI)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_SphericalChebyshev_backward1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jint, jdouble, jint, jint, jboolean, jint, jboolean, jint, jboolean, jint, jint, jdoubleArray, jint);

/*
 * Class:     jsex_nnap_basis_SphericalChebyshev
 * Method:    forwardForce1
 * Signature: ([D[D[D[II[DI[D[D[D[DI[DIZIDIIZIZIZI[DI[DI)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_SphericalChebyshev_forwardForce1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdoubleArray, jint, jboolean, jint, jdouble, jint, jint, jboolean, jint, jboolean, jint, jboolean, jint, jdoubleArray, jint, jdoubleArray, jint);

/*
 * Class:     jsex_nnap_basis_SphericalChebyshev
 * Method:    backwardForce1
 * Signature: ([D[D[D[II[DI[D[D[D[DI[DI[DI[DI[DI[DIZIDIIZIZIZI[DI[DI)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_SphericalChebyshev_backwardForce1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jboolean, jint, jdouble, jint, jint, jboolean, jint, jboolean, jint, jboolean, jint, jdoubleArray, jint, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
