/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsex_nnap_basis_Chebyshev */

#ifndef _Included_jsex_nnap_basis_Chebyshev
#define _Included_jsex_nnap_basis_Chebyshev
#ifdef __cplusplus
extern "C" {
#endif
#undef jsex_nnap_basis_Chebyshev_WTYPE_DEFAULT
#define jsex_nnap_basis_Chebyshev_WTYPE_DEFAULT 0L
#undef jsex_nnap_basis_Chebyshev_WTYPE_NONE
#define jsex_nnap_basis_Chebyshev_WTYPE_NONE -1L
#undef jsex_nnap_basis_Chebyshev_WTYPE_FULL
#define jsex_nnap_basis_Chebyshev_WTYPE_FULL 2L
#undef jsex_nnap_basis_Chebyshev_WTYPE_EXFULL
#define jsex_nnap_basis_Chebyshev_WTYPE_EXFULL 3L
#undef jsex_nnap_basis_Chebyshev_WTYPE_FUSE
#define jsex_nnap_basis_Chebyshev_WTYPE_FUSE 4L
#undef jsex_nnap_basis_Chebyshev_WTYPE_EXFUSE
#define jsex_nnap_basis_Chebyshev_WTYPE_EXFUSE 6L
#undef jsex_nnap_basis_Chebyshev_FUSE_STYLE_LIMITED
#define jsex_nnap_basis_Chebyshev_FUSE_STYLE_LIMITED 0L
#undef jsex_nnap_basis_Chebyshev_FUSE_STYLE_EXTENSIVE
#define jsex_nnap_basis_Chebyshev_FUSE_STYLE_EXTENSIVE 1L
#undef jsex_nnap_basis_Chebyshev_DEFAULT_NMAX
#define jsex_nnap_basis_Chebyshev_DEFAULT_NMAX 5L
#undef jsex_nnap_basis_Chebyshev_DEFAULT_RCUT
#define jsex_nnap_basis_Chebyshev_DEFAULT_RCUT 6.0
/*
 * Class:     jsex_nnap_basis_Chebyshev
 * Method:    calSystemScale1
 * Signature: ([D[D[D[II[DI[DIIDIII[D[D)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_Chebyshev_calSystemScale1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jint, jdoubleArray, jint, jint, jdouble, jint, jint, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     jsex_nnap_basis_Chebyshev
 * Method:    forward1
 * Signature: ([D[D[D[II[DI[DIZIDIII[DI[D[D[D)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_Chebyshev_forward1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jint, jdoubleArray, jint, jboolean, jint, jdouble, jint, jint, jint, jdoubleArray, jint, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     jsex_nnap_basis_Chebyshev
 * Method:    backward1
 * Signature: ([D[D[D[II[DI[DI[DI[DIIDIIII[D)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_Chebyshev_backward1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jint, jdouble, jint, jint, jint, jint, jdoubleArray);

/*
 * Class:     jsex_nnap_basis_Chebyshev
 * Method:    forwardForce1
 * Signature: ([D[D[D[II[DI[D[D[D[DI[DIZIDIII[DI[D[D)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_Chebyshev_forwardForce1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdoubleArray, jint, jboolean, jint, jdouble, jint, jint, jint, jdoubleArray, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     jsex_nnap_basis_Chebyshev
 * Method:    backwardForce1
 * Signature: ([D[D[D[II[DI[D[D[D[DI[DI[DI[DI[DI[DIZIDIII[DI[D)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_basis_Chebyshev_backwardForce1
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdoubleArray, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jboolean, jint, jdouble, jint, jint, jint, jdoubleArray, jint, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
