/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsex_nnap_NNAP */

#ifndef _Included_jsex_nnap_NNAP
#define _Included_jsex_nnap_NNAP
#ifdef __cplusplus
extern "C" {
#endif
#undef jsex_nnap_NNAP_VERSION
#define jsex_nnap_NNAP_VERSION 3L
#undef jsex_nnap_NNAP_BATCH_SIZE
#define jsex_nnap_NNAP_BATCH_SIZE 64L
/*
 * Class:     jsex_nnap_NNAP
 * Method:    setSingleThread0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_NNAP_setSingleThread0
  (JNIEnv *, jclass);

/*
 * Class:     jsex_nnap_NNAP
 * Method:    load0
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jsex_nnap_NNAP_load0
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jsex_nnap_NNAP
 * Method:    load1
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_jsex_nnap_NNAP_load1
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     jsex_nnap_NNAP
 * Method:    forward0
 * Signature: (J[DII)D
 */
JNIEXPORT jdouble JNICALL Java_jsex_nnap_NNAP_forward0
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jint);

/*
 * Class:     jsex_nnap_NNAP
 * Method:    forward1
 * Signature: (JJI)D
 */
JNIEXPORT jdouble JNICALL Java_jsex_nnap_NNAP_forward1
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     jsex_nnap_NNAP
 * Method:    batchForward0
 * Signature: (J[DII[DII)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_NNAP_batchForward0
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jint, jdoubleArray, jint, jint);

/*
 * Class:     jsex_nnap_NNAP
 * Method:    batchForward1
 * Signature: (JJIJI)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_NNAP_batchForward1
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jint);

/*
 * Class:     jsex_nnap_NNAP
 * Method:    backward0
 * Signature: (J[DI[DII)D
 */
JNIEXPORT jdouble JNICALL Java_jsex_nnap_NNAP_backward0
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jdoubleArray, jint, jint);

/*
 * Class:     jsex_nnap_NNAP
 * Method:    backward1
 * Signature: (JJJI)D
 */
JNIEXPORT jdouble JNICALL Java_jsex_nnap_NNAP_backward1
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     jsex_nnap_NNAP
 * Method:    batchBackward0
 * Signature: (J[DI[DII[DII)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_NNAP_batchBackward0
  (JNIEnv *, jclass, jlong, jdoubleArray, jint, jdoubleArray, jint, jint, jdoubleArray, jint, jint);

/*
 * Class:     jsex_nnap_NNAP
 * Method:    batchBackward1
 * Signature: (JJJIJI)V
 */
JNIEXPORT void JNICALL Java_jsex_nnap_NNAP_batchBackward1
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
