#!/bin/bash

# 获取脚本所在的目录
PRG="$0"
while [ -h "$PRG" ] ; do
    ls="$(ls -ld "$PRG")"
    link="$(expr "$ls" : '.*-> \(.*\)$')"
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG="$(dirname "$PRG")"/"$link"
    fi
done
SCRIPT_DIR="$(dirname "$PRG")"

# 查找 jse.jar 的位置
JAR_LOCATION=""
for i in "$SCRIPT_DIR"/jse-*.jar; do
    if [ -e "$i" ]; then
    JAR_LOCATION="$i"
    break
    fi
done
if [ -z "$JAR_LOCATION" ]; then
for i in "$SCRIPT_DIR"/lib/jse-*.jar; do
    if [ -e "$i" ]; then
    JAR_LOCATION="$i"
    break
    fi
done
fi


# 检查是否找到了 jse.jar
if [ -z "$JAR_LOCATION" ]; then
echo "Error: jse-*.jar not found"
exit 1
fi

# 设置 UTF-8
JAVA_OPTS="$JAVA_OPTS -Dfile.encoding=UTF-8"

# 消除每 30s 一次的 prefs 的警告
JAVA_OPTS="$JAVA_OPTS -Djava.util.prefs.syncInterval=1000000"

# SLURM_PROCID 环境变量存在且不为 0 时限制内存大小
if [ -n "$SLURM_PROCID" ] && [ "$SLURM_PROCID" -ne 0 ]; then
JAVA_OPTS="$JAVA_OPTS -Xmx1g"
fi

# 执行 jse.jar
java $JAVA_OPTS -jar "$JAR_LOCATION" "$@"
