#!/usr/bin/env bash

# Get the directory where the script is located
PRG="$0"
while [ -h "$PRG" ] ; do
    ls="$(ls -ld "$PRG")"
    link="$(expr "$ls" : '.*-> \(.*\)$')"
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG="$(dirname "$PRG")"/"$link"
    fi
done
SCRIPT_DIR="$(dirname "$PRG")"

# Find jse.jar
JAR_LOCATION=""
for i in "$SCRIPT_DIR"/jse-*.jar; do
    if [ -e "$i" ]; then
    JAR_LOCATION="$i"
    break
    fi
done
if [ -z "$JAR_LOCATION" ]; then
for i in "$SCRIPT_DIR"/lib/jse-*.jar; do
    if [ -e "$i" ]; then
    JAR_LOCATION="$i"
    break
    fi
done
fi


# Check if jse.jar has been found
if [ -z "$JAR_LOCATION" ]; then
    echo "Error: jse-*.jar not found"
    exit 1
fi


# Eliminate the every 30s prefs warning
JAVA_OPTS="$JAVA_OPTS -Djava.util.prefs.syncInterval=1000000"

# Restrict memory size when the SLURM_PROCID environment variable exists and is not 0
if [ -n "$SLURM_PROCID" ] && [ "$SLURM_PROCID" -ne 0 ]; then
    JAVA_OPTS="$JAVA_OPTS -Xmx1g"
fi

# Set headless for SLURM in default
if [ -n "$SLURM_NODELIST" ] || { [ -n "$JSE_HEADLESS" ] && [ "$JSE_HEADLESS" -ne 0 ]; }; then
    JAVA_OPTS="$JAVA_OPTS -Djava.awt.headless=true"
fi

# Execute jse.jar
java $JAVA_OPTS -jar "$JAR_LOCATION" BASH "$@"
