#!/usr/bin/env sh

# 获取脚本所在的目录
PRG="$0"
while [ -h "$PRG" ] ; do
    ls="$(ls -ld "$PRG")"
    link="$(expr "$ls" : '.*-> \(.*\)$')"
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG="$(dirname "$PRG")"/"$link"
    fi
done
SCRIPT_DIR="$(dirname "$PRG")"

# 查找 jTool.jar 的位置
JAR_LOCATION=""
for i in "$SCRIPT_DIR"/jTool-*.jar; do
    if [ -e "$i" ]; then
    JAR_LOCATION="$i"
    break
    fi
done
if [ -z "$JAR_LOCATION" ]; then
for i in "$SCRIPT_DIR"/include/jTool-*.jar; do
    if [ -e "$i" ]; then
    JAR_LOCATION="$i"
    break
    fi
done
fi
if [ -z "$JAR_LOCATION" ]; then
for i in "$SCRIPT_DIR"/lib/jTool-*.jar; do
    if [ -e "$i" ]; then
    JAR_LOCATION="$i"
    break
    fi
done
fi
if [ -z "$JAR_LOCATION" ]; then
for i in "$SCRIPT_DIR"/libs/jTool-*.jar; do
    if [ -e "$i" ]; then
    JAR_LOCATION="$i"
    break
    fi
done
fi
if [ -z "$JAR_LOCATION" ]; then
for i in "$SCRIPT_DIR"/jar/jTool-*.jar; do
    if [ -e "$i" ]; then
    JAR_LOCATION="$i"
    break
    fi
done
fi
if [ -z "$JAR_LOCATION" ]; then
for i in "$SCRIPT_DIR"/java/jTool-*.jar; do
    if [ -e "$i" ]; then
    JAR_LOCATION="$i"
    break
    fi
done
fi

# 检查是否找到了 jTool.jar
if [ -z "$JAR_LOCATION" ]; then
echo "Error: jTool-*.jar not found"
exit 1
fi

# 执行 jTool.jar
java -jar "$JAR_LOCATION" "$@"
