/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jse_gpu_CudaNeighborListGetter */

#ifndef _Included_jse_gpu_CudaNeighborListGetter
#define _Included_jse_gpu_CudaNeighborListGetter
#ifdef __cplusplus
extern "C" {
#endif
#undef jse_gpu_CudaNeighborListGetter_MAX_SLICE
#define jse_gpu_CudaNeighborListGetter_MAX_SLICE 512L
/*
 * Class:     jse_gpu_CudaNeighborListGetter
 * Method:    initPosTypeLmp0
 * Signature: (IIFFFJJJJJJZIJ)I
 */
JNIEXPORT jint JNICALL Java_jse_gpu_CudaNeighborListGetter_initPosTypeLmp0
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jlong, jlong, jlong, jlong, jlong, jlong, jboolean, jint, jlong);

/*
 * Class:     jse_gpu_CudaNeighborListGetter
 * Method:    initCells0
 * Signature: (IIIJJJII)I
 */
JNIEXPORT jint JNICALL Java_jse_gpu_CudaNeighborListGetter_initCells0
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jlong, jint, jint);

/*
 * Class:     jse_gpu_CudaNeighborListGetter
 * Method:    buildCells0
 * Signature: (IIIZFFFFFFFFFJIIIJJJIIJJ)I
 */
JNIEXPORT jint JNICALL Java_jse_gpu_CudaNeighborListGetter_buildCells0
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jlong, jint, jint, jint, jlong, jlong, jlong, jint, jint, jlong, jlong);

/*
 * Class:     jse_gpu_CudaNeighborListGetter
 * Method:    buildNl0
 * Signature: (IIIZFFFFFFFFFJIIIJJFJJJIJ)I
 */
JNIEXPORT jint JNICALL Java_jse_gpu_CudaNeighborListGetter_buildNl0
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jlong, jint, jint, jint, jlong, jlong, jfloat, jlong, jlong, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
